import {backoffMs,MAX_ATTEMPTS,sortJobs,TIMEOUT_MS} from "./notification-engine.mjs";
const jobs=new Map(),attempts=new Map(),audit=[];
const now=()=>new Date().toISOString();
export function enqueue({alertId,target,payload,channel="webhook",at=new Date().toISOString(),timeoutMs=TIMEOUT_MS}){const idempotencyKey=`${channel}:${alertId}:${target}`;const existing=[...jobs.values()].find(j=>j.idempotencyKey===idempotencyKey&&!(["DEAD_LETTER","CANCELLED"].includes(j.status)));if(existing)return existing;const id=`delivery:${Buffer.from(idempotencyKey).toString("base64url")}`;const job={id,alertId,channel,target,payload,status:"PENDING",attempts:0,createdAt:at,updatedAt:at,nextAttemptAt:null,lastError:null,idempotencyKey,timeoutMs};jobs.set(id,job);audit.push({type:"ENQUEUED",jobId:id,at,alertId});return job}
export function listJobs(){return sortJobs([...jobs.values()])}
export function getJob(id){return jobs.get(id)||null}
export function listAttempts(id){return [...(attempts.get(id)||[])]}
export function auditLog(){return [...audit]}
export function cancelJob(id){const job=jobs.get(id);if(!job||["SUCCESS","DEAD_LETTER","CANCELLED"].includes(job.status))return null;const next={...job,status:"CANCELLED",updatedAt:now(),nextAttemptAt:null};jobs.set(id,next);audit.push({type:"CANCELLED",jobId:id,at:next.updatedAt});return next}
function update(job,patch){const next={...job,...patch,updatedAt:now()};jobs.set(job.id,next);return next}
export async function deliverJob(id,fetchImpl=globalThis.fetch){let job=jobs.get(id);if(!job||["SUCCESS","DEAD_LETTER","CANCELLED"].includes(job.status))return job;const attemptNo=job.attempts+1;const started=now();job=update(job,{status:"RUNNING",attempts:attemptNo});const attemptId=`attempt:${job.id}:${attemptNo}`;let timer;try{const controller=new AbortController();timer=setTimeout(()=>controller.abort(),job.timeoutMs);timer.unref?.();const response=await fetchImpl(job.target,{method:"POST",headers:{"content-type":"application/json","x-atlas-idempotency-key":job.idempotencyKey},body:JSON.stringify(job.payload),signal:controller.signal});clearTimeout(timer);if(!response.ok)throw new Error(`HTTP_${response.status}`);const finished=now();const record={id:attemptId,jobId:job.id,attempt:attemptNo,status:"SUCCESS",startedAt:started,finishedAt:finished,error:null,adapter:"webhook"};attempts.set(id,[...(attempts.get(id)||[]),record]);audit.push({type:"DELIVERED",jobId:id,attempt:attemptNo,at:finished});return update(job,{status:"SUCCESS",lastError:null,nextAttemptAt:null})}catch(error){if(timer)clearTimeout(timer);const message=error?.name==="AbortError"?"TIMEOUT":String(error?.message||error);const terminal=attemptNo>=MAX_ATTEMPTS;const finished=now();const status=terminal?"DEAD_LETTER":"RETRYING";const record={id:attemptId,jobId:job.id,attempt:attemptNo,status,startedAt:started,finishedAt:finished,error:message,adapter:"webhook"};attempts.set(id,[...(attempts.get(id)||[]),record]);audit.push({type:terminal?"DEAD_LETTER":"RETRY",jobId:id,attempt:attemptNo,at:finished,error:message});return update(job,{status,lastError:message,nextAttemptAt:terminal?null:new Date(Date.now()+backoffMs(attemptNo)).toISOString()})}}
export function clearNotificationStore(){jobs.clear();attempts.clear();audit.length=0}
