const FIELDS=["title","description","category","subcategory","provider","sourceOrganization","country","region","city","locationLabel","canonicalId","tags"];
function norm(value){return String(value??"").normalize("NFKC").trim().toLocaleLowerCase("en-US")}
function tokens(value){return norm(value).split(/[^\p{L}\p{N}]+/u).filter(Boolean)}
function haystack(document){return FIELDS.flatMap(field=>Array.isArray(document[field])?document[field]:[document[field]]).map(norm).join(" ")}
export function matchWatchlist(document,target){const value=norm(target.value);if(!value)return null;const fieldMap={country:[document.country],organization:[document.sourceOrganization],provider:[document.provider],category:[document.category],"risk-level":[document.riskLevel],location:[document.locationLabel,document.city,document.region,document.country],entity:[document.canonicalId,document.title],"search-query":[haystack(document)]};const values=(fieldMap[target.type]??[]).map(norm).filter(Boolean);if(target.type==="search-query"){const wanted=tokens(value);if(wanted.length&&wanted.every(token=>haystack(document).includes(token)))return `Search query matched all tokens: ${wanted.join(", ")}`;return null}if(values.some(item=>item===value))return `${target.type} matched exactly: ${target.value}`;if(target.type==="entity"&&values.some(item=>item.includes(value)))return `Entity reference matched canonical field: ${target.value}`;return null}
function stableId(value){let hash=2166136261;for(const char of value){hash^=char.codePointAt(0);hash=Math.imul(hash,16777619)}return(hash>>>0).toString(36)}
export function evaluateWatchlists(watchlists,index){const alerts=[];for(const watchlist of watchlists.filter(item=>item.enabled)){for(const document of index.documents){const reason=matchWatchlist(document,watchlist.target);if(reason)alerts.push({id:`alert:${watchlist.id}:${document.canonicalId}:${stableId(document.occurredAt)}`,watchlistId:watchlist.id,canonicalId:document.canonicalId,timestamp:document.occurredAt,matchingReason:reason,status:"NEW",document})}}return alerts.sort((a,b)=>Date.parse(b.timestamp)-Date.parse(a.timestamp)||a.watchlistId.localeCompare(b.watchlistId)||a.canonicalId.localeCompare(b.canonicalId))}
export function summarizeWatchlists(watchlists,alerts,generatedAt,warnings=[]){const counts={NEW:0,READ:0,DISMISSED:0};for(const alert of alerts)counts[alert.status]++;return{totalWatchlists:watchlists.length,enabledWatchlists:watchlists.filter(x=>x.enabled).length,totalAlerts:alerts.length,newAlerts:counts.NEW,readAlerts:counts.READ,dismissedAlerts:counts.DISMISSED,latestMatchAt:alerts[0]?.timestamp??null,degraded:warnings.length>0,warnings,generatedAt}}
export function sortWatchlists(items){return[...items].sort((a,b)=>a.name.localeCompare(b.name)||a.id.localeCompare(b.id))}
