import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { filterTechnologies,parseRadarQuery,stableRadarSort } from "../src/lib/ai-radar/ai-radar-logic.mjs";

const provenance={providerId:"fixture",sourceUrl:"https://example.test/official",sourceName:"Official",retrievedAt:"2026-07-25T00:00:00.000Z",attribution:"Official source"};
const technology=(overrides={})=>({id:"alpha",name:"Alpha",developer:"Example",category:"model",summary:"Verified model",license:"Apache-2.0",openSource:true,openWeights:true,commercial:true,apiAvailable:true,localDeployment:{status:"supported",ramGb:null,vramGb:null,cpu:null,gpu:null,quantization:[],exampleHardware:null,runtimes:["vLLM"],provenance},contextWindow:null,releaseDate:"2026-07-20",version:"1",status:"active",tags:["coding"],capabilities:[{id:"coding",supported:true,provenance}],links:[],provenance:[provenance],...overrides});
const snapshot={radarVersion:"atlas-ai-radar-v1",generatedAt:"2026-07-25T00:00:00.000Z",partial:false,stale:false,providers:[{id:"z",name:"Z",kind:"registry",state:"operational",checkedAt:"2026-07-25T00:00:00.000Z",itemCount:1},{id:"a",name:"A",kind:"benchmark",state:"operational",checkedAt:"2026-07-25T00:00:00.000Z",itemCount:1}],technologies:[technology({id:"z",name:"Zulu"}),technology()],releases:[{id:"older",technologyId:"alpha",name:"Old",company:"Example",category:"model",version:"1",releaseDate:"2026-07-20",summary:"Official",links:[],provenance},{id:"newer",technologyId:"alpha",name:"New",company:"Example",category:"model",version:"2",releaseDate:"2026-07-24",summary:"Official",links:[],provenance}],benchmarks:[{id:"b",technologyId:null,technologyName:"B",benchmark:"SWE-bench",benchmarkVersion:"Verified",score:50,unit:"percent",evaluationDate:"2026-01-01",testConfiguration:"B",hardware:null,officialSourceUrl:provenance.sourceUrl,provenance},{id:"a",technologyId:null,technologyName:"A",benchmark:"SWE-bench",benchmarkVersion:"Verified",score:60,unit:"percent",evaluationDate:"2026-01-01",testConfiguration:"A",hardware:null,officialSourceUrl:provenance.sourceUrl,provenance}],inputSummary:{technologyCount:2,releaseCount:2,benchmarkCount:2,respondingProviders:2,failedProviders:0}};

test("stable ordering and identical input are reproducible",()=>{const a=stableRadarSort(snapshot),b=stableRadarSort(snapshot);assert.deepEqual(a,b);assert.deepEqual(a.providers.map(x=>x.id),["a","z"]);assert.deepEqual(a.releases.map(x=>x.id),["newer","older"]);assert.deepEqual(a.benchmarks.map(x=>x.id),["a","b"])});
test("directory filtering is exact and deterministic",()=>{const items=[technology(),technology({id:"closed",name:"Closed",developer:"Other",openSource:false,apiAvailable:false,localDeployment:{...technology().localDeployment,status:"not-supported"},capabilities:[]})];assert.deepEqual(filterTechnologies(items,{search:"coding",openSource:true,api:true,local:true,capability:"coding"},"2026-07-25T00:00:00.000Z").map(x=>x.id),["alpha"]);assert.deepEqual(filterTechnologies(items,{released:"week"},"2026-07-25T00:00:00.000Z").map(x=>x.id),["alpha","closed"])});
test("query validation rejects unknown and unbounded input",()=>{assert.equal(parseRadarQuery(new URLSearchParams("category=unknown")).code,"INVALID_CATEGORY");assert.equal(parseRadarQuery(new URLSearchParams("capability=emotion")).code,"INVALID_CAPABILITY");assert.equal(parseRadarQuery(new URLSearchParams("openSource=yes")).code,"INVALID_BOOLEAN");assert.equal(parseRadarQuery(new URLSearchParams("limit=101")).code,"INVALID_LIMIT");assert.equal(parseRadarQuery(new URLSearchParams("extra=x")).code,"INVALID_PARAMETERS");assert.equal(parseRadarQuery(new URLSearchParams("category=model&openSource=true&limit=10")).ok,true)});
test("official registry never fabricates hardware or context values",async()=>{const text=await readFile(new URL("../src/lib/ai-radar/ai-radar-registry.ts",import.meta.url),"utf8");assert.match(text,/ramGb: null, vramGb: null/);assert.match(text,/contextWindow: input\.context \?\? null/);assert.doesNotMatch(text,/ranking/i)});
test("providers, APIs, cache, partial and stale behavior are explicit",async()=>{const files=await Promise.all(["../src/lib/ai-radar/ai-radar-providers.ts","../src/lib/ai-radar/ai-radar-service.ts","../src/app/api/ai/route.ts","../src/app/api/ai/releases/route.ts","../src/app/api/ai/benchmarks/route.ts","../src/app/api/ai/technology/route.ts"].map(path=>readFile(new URL(path,import.meta.url),"utf8")));assert.match(files[0],/api\.github\.com/);assert.match(files[0],/swe-bench\.github\.io/);assert.match(files[0],/no scores substituted/);assert.match(files[1],/stale:true/);assert.match(files[2],/parseRadarQuery/);assert.equal(files.slice(2).length,4)});
test("page and dashboard state provenance and no-ranking rule",async()=>{const [page,dashboard,docs]=await Promise.all([readFile(new URL("../src/components/ai-radar/AiRadarExplorer.tsx",import.meta.url),"utf8"),readFile(new URL("../src/components/ai-radar/DashboardAiRadar.tsx",import.meta.url),"utf8"),readFile(new URL("../../../docs/ATLAS-AI-RADAR.md",import.meta.url),"utf8")]);assert.match(page,/No generated rankings/);assert.match(page,/Not published/);assert.match(dashboard,/Partial official coverage/);assert.match(docs,/never fabricates benchmark scores/i);assert.match(docs,/provenance/)});
