import test from "node:test";import assert from "node:assert/strict";
import {canTransition,deduplicateAlerts,filterAlerts,parseAlertQuery,summarizeAlerts} from "../src/lib/alerts/alert-engine.mjs";
import {auditFor,clearAlertStore,statusFor,transition} from "../src/lib/alerts/alert-store.mjs";
const base={alertId:"risk:evt-1",source:"risk",sourceRecordId:"evt-1",severity:"HIGH",priority:"high",status:"NEW",canonicalReference:{canonicalId:"evt-1",path:"/app/events/evt-1",type:"event"},matchingReason:"Canonical high severity",title:"Verified event",category:"earthquake",riskLevel:"HIGH",createdAt:"2026-07-26T10:00:00.000Z",updatedAt:"2026-07-26T10:00:00.000Z",occurredAt:"2026-07-26T09:00:00.000Z",provenance:[{providerId:"usgs",attribution:"USGS",sourceUrl:"https://example.test",producer:"risk",sourceRecordId:"evt-1"}],metadata:{ruleId:"R1"}};
test("lifecycle transitions are deterministic and terminal archive is protected",()=>{assert.equal(canTransition("NEW","ACKNOWLEDGED"),true);assert.equal(canTransition("NEW","ARCHIVED"),false);assert.equal(canTransition("ARCHIVED","READ"),false);clearAlertStore();assert.equal(statusFor("a"),"NEW");transition("a","ACKNOWLEDGED","2026-07-26T10:00:00.000Z");assert.equal(statusFor("a"),"ACKNOWLEDGED");assert.equal(auditFor("a").length,1);clearAlertStore()});
test("deduplication and ordering preserve alert identity",()=>{const newer={...base,updatedAt:"2026-07-26T11:00:00.000Z"},other={...base,alertId:"breaking:evt-2",source:"breaking",occurredAt:"2026-07-26T11:00:00.000Z"};assert.equal(deduplicateAlerts([base,newer,other]).length,2);assert.deepEqual(deduplicateAlerts([base,newer,other]).map(x=>x.alertId),["breaking:evt-2","risk:evt-1"])});
test("filters support status severity source category risk dates search and stable sorts",()=>{const other={...base,alertId:"watchlists:match",source:"watchlists",status:"READ",severity:"INFORMATIONAL",riskLevel:null,occurredAt:"2026-07-25T09:00:00.000Z"};const filters={statuses:["READ"],severities:[],sources:["watchlists"],categories:[],riskLevels:[],from:"2026-07-25T00:00:00.000Z",to:"2026-07-26T00:00:00.000Z",search:"match",sort:"newest",page:1,pageSize:25};assert.deepEqual(filterAlerts([base,other],filters).map(x=>x.alertId),["watchlists:match"]);assert.equal(parseAlertQuery(new URLSearchParams("status=NEW&severity=HIGH&source=risk&sort=severity&pageSize=10")).ok,true);assert.equal(parseAlertQuery(new URLSearchParams("status=BOGUS")).ok,false)});
test("summary exposes all lifecycle, severity, and source distributions",()=>{const summary=summarizeAlerts([base,{...base,alertId:"breaking:x",source:"breaking",severity:"CRITICAL",status:"DISMISSED"}],"2026-07-26T12:00:00.000Z");assert.equal(summary.total,2);assert.equal(summary.statusCounts.NEW,1);assert.equal(summary.statusCounts.DISMISSED,1);assert.equal(summary.severityCounts.CRITICAL,1);assert.equal(summary.sourceCounts.risk,1)});
test("API, routes, UI, navigation, and consolidated evidence boundaries are present",async()=>{const fs=await import("node:fs/promises"),api=await fs.readFile(new URL("../src/app/api/alerts/route.ts",import.meta.url),"utf8"),detail=await fs.readFile(new URL("../src/app/app/alerts/[alertId]/page.tsx",import.meta.url),"utf8"),ui=await fs.readFile(new URL("../src/components/alerts/AlertCenter.tsx",import.meta.url),"utf8"),docs=await fs.readFile(new URL("../../../docs/STANDARDS.md",import.meta.url),"utf8");assert.match(api,/listAlerts/);assert.match(detail,/Provenance/);assert.match(ui,/Severity/);assert.match(docs,/Evidence First/)});
