import test from "node:test";
import assert from "node:assert/strict";
import {buildSearchIndex} from "../src/lib/search/search-index.mjs";
import {buildEntityGraph} from "../src/lib/graph/entity-graph-builder.mjs";
import {entityBaseId,normalizeEntityValue,resolveEntityIds} from "../src/lib/graph/entity-normalization.mjs";
import {entityDetail,parseEntityQuery,queryEntities,relationshipsForEntity,traverseGraph} from "../src/lib/graph/entity-graph-query.mjs";
import {serializeEntityState} from "../src/lib/graph/entity-url-state.mjs";
import {clearEntityGraphCache,withEntityGraphCache} from "../src/lib/graph/entity-graph-cache.mjs";

const NOW="2026-07-26T12:00:00.000Z";
function searchIndex(degradedModules=[]){return buildSearchIndex({
  risk:{alerts:[{canonicalId:"evt-1",level:"HIGH",explanation:"Existing canonical classification.",sourceEventId:"timeline:event:evt-1",sourceCategory:"earthquake",sourceAttribution:"USGS attribution",canonicalTarget:"/app/events/evt-1",title:"Verified Japan earthquake",providerId:"usgs-earthquakes",providerName:"USGS",priority:"high",location:"Honshu, Japan",occurredAt:"2026-07-26T10:00:00.000Z",updatedAt:"2026-07-26T10:30:00.000Z",latitude:35,longitude:139,mapTarget:"/app/map?event=evt-1&focus=1",timelineTarget:"/app/timeline?search=earthquake"}]},
  breaking:{events:[{canonicalId:"evt-1",providerName:"USGS",providerId:"usgs-earthquakes",sourceUrl:"https://example.test/evt-1",provenance:{attribution:"USGS attribution"}}]},
  radar:{technologies:[{id:"tech-1",name:"Atlas Model",developer:"Example AI",category:"model",summary:"Official model release",releaseDate:"2026-07-25T00:00:00.000Z",links:[{label:"Model card",url:"https://example.test/model"}],tags:["reasoning"],capabilities:[],provenance:[{providerId:"ai-registry",attribution:"Official registry",sourceUrl:"https://example.test/model"}]}]},
  reportTypes:[{id:"daily-global",label:"Daily Global Report",defaultHistory:"24h",categories:["earthquake"],description:"Verified daily report"}],
  generatedAt:NOW,degradedModules
})}
function graph(degraded=[]){return buildEntityGraph(searchIndex(degraded))}
const filters={q:"",entityTypes:[],nodeTypes:[],categories:[],country:"",region:"",provider:"",risks:[],relationshipType:"",direction:"",page:1,pageSize:25,sort:"label-asc"};

test("normalization and collision handling produce stable locale-safe entity IDs",()=>{assert.equal(normalizeEntityValue("  U.S.G.S.  "),"u-s-g-s");assert.equal(entityBaseId("DATA_PROVIDER","USGS"),"entity:data-provider:usgs");const items=[{key:"a",entityType:"ORGANIZATION",label:"A+B"},{key:"b",entityType:"ORGANIZATION",label:"A B"}],one=resolveEntityIds(items),two=resolveEntityIds([...items].reverse());assert.equal(one.get("a"),two.get("a"));assert.notEqual(one.get("a"),one.get("b"))});
test("graph nodes and directed edges preserve explicit evidence and attribution",()=>{const value=graph(),event=value.nodes.find(x=>x.canonicalId==="evt-1"&&x.nodeType==="EVENT"),provider=value.nodes.find(x=>x.entityType==="DATA_PROVIDER"),edge=value.edges.find(x=>x.sourceNodeId===event.nodeId&&x.targetNodeId===provider.nodeId);assert.equal(edge.relationshipType,"PROVIDED_BY");assert.equal(edge.direction,"DIRECTED");assert.equal(edge.evidenceCanonicalId,"evt-1");assert.equal(edge.confidencePolicy,"EXPLICIT_CANONICAL_FIELD");assert.match(edge.provenance[0].attribution,/USGS/)});
test("canonical records and relationships deduplicate with stable ordering",()=>{const value=graph();assert.equal(new Set(value.nodes.map(x=>x.nodeId)).size,value.nodes.length);assert.equal(new Set(value.edges.map(x=>x.edgeId)).size,value.edges.length);assert.deepEqual(value.nodes.map(x=>x.nodeId),[...value.nodes.map(x=>x.nodeId)].sort());assert.deepEqual(value.edges.map(x=>x.edgeId),[...value.edges.map(x=>x.edgeId)].sort())});
test("unsupported inferred and report relationships are never created",()=>{const types=graph().edges.map(x=>x.relationshipType);assert.equal(types.includes("CO_OCCURS_WITH"),false);assert.equal(types.includes("INCLUDED_IN_REPORT"),false);assert.equal(types.includes("REFERENCES_ENTITY"),false)});
test("partial graph generation exposes degraded modules without replacement data",()=>{const value=graph(["reports"]);assert.equal(value.status.degradedModules.includes("reports"),true);assert.equal(value.status.warnings.length>0,true)});
test("entity filters facets sorting and pagination are deterministic",()=>{const value=graph(),all=queryEntities(value,filters),providers=queryEntities(value,{...filters,entityTypes:["DATA_PROVIDER"]}),paged=queryEntities(value,{...filters,pageSize:1,page:2}),connected=queryEntities(value,{...filters,sort:"most-connected"});assert.ok(all.facets.entityTypes.length);assert.equal(providers.entities.every(x=>x.entityType==="DATA_PROVIDER"),true);assert.equal(paged.entities.length,1);assert.ok(connected.entities[0].relationshipCount>=connected.entities.at(-1).relationshipCount);assert.equal(queryEntities(value,{...filters,q:"not-present"}).totalEntities,0)});
test("detail, directions, relationship filtering and existing-risk aggregation work",()=>{const value=graph(),provider=value.nodes.find(x=>x.entityType==="DATA_PROVIDER"),detail=entityDetail(value,provider.nodeId),incoming=relationshipsForEntity(value,provider.nodeId,{relationshipType:"PROVIDED_BY",direction:"incoming"});assert.ok(detail.connectedNodes.length);assert.equal(incoming.every(x=>x.targetNodeId===provider.nodeId),true);assert.equal(detail.entity.aggregateRisk,"HIGH");assert.match(detail.entity.searchPath,/app\/search/)});
test("traversal depth and explosion bounds are enforced",()=>{const value=graph(),root=value.nodes.find(x=>x.entityType),one=traverseGraph(value,root.nodeId,1),two=traverseGraph(value,root.nodeId,99);assert.equal(one.depth,1);assert.equal(two.depth,2);assert.ok(two.nodes.length<=100);assert.ok(two.edges.length<=200);assert.equal(traverseGraph(value,"missing"),null)});
test("map links require verified coordinates and official sources retain URLs",()=>{const value=graph(),map=value.nodes.find(x=>x.nodeType==="MAP_EVENT"),source=value.nodes.find(x=>x.nodeType==="OFFICIAL_SOURCE");assert.match(map.canonicalPath,/\/app\/map/);assert.match(source.canonicalPath,/^https:/);assert.equal(source.provenance[0].attribution,"USGS attribution")});
test("URL state and query contracts are reproducible",()=>{const parsed=parseEntityQuery(new URLSearchParams("q=usgs&entityType=DATA_PROVIDER&relationshipType=PROVIDED_BY&direction=incoming&page=2"));assert.equal(parsed.ok,true);assert.match(serializeEntityState(parsed.filters),/entityType=DATA_PROVIDER/);assert.equal(parseEntityQuery(new URLSearchParams("depth=99")).ok,false)});
test("cache stale fallback remains explicit and never fabricates a graph",async()=>{clearEntityGraphCache();const value=graph();await withEntityGraphCache("graph",10,20,async()=>value,100);const stale=await withEntityGraphCache("graph",10,20,async()=>{throw new Error("offline")},115);assert.equal(stale.nodes.length,value.nodes.length);assert.ok(stale.status.degradedModules.includes("graph-refresh"))});
test("UI, API, navigation and responsive contracts are present",async()=>{const fs=await import("node:fs/promises"),api=await fs.readFile(new URL("../src/app/api/entities/route.ts",import.meta.url),"utf8"),detail=await fs.readFile(new URL("../src/app/api/entities/[entityId]/route.ts",import.meta.url),"utf8"),ui=await fs.readFile(new URL("../src/components/entities/EntityKnowledgeGraph.tsx",import.meta.url),"utf8"),desktop=await fs.readFile(new URL("../src/components/dashboard/AtlasSidebar.tsx",import.meta.url),"utf8"),mobile=await fs.readFile(new URL("../src/components/mobile/AtlasMobileOverview.tsx",import.meta.url),"utf8"),css=await fs.readFile(new URL("../src/app/app/dashboard.css",import.meta.url),"utf8");assert.match(api,/getEntities/);assert.match(detail,/getEntity/);assert.match(ui,/Entity Knowledge Graph/);assert.match(desktop,/Knowledge Graph/);assert.match(mobile,/href="\/app\/entities"/);assert.match(css,/\.entity-table-wrap/);assert.match(css,/@media \(max-width:700px\)/)});
