import test from "node:test";
import assert from "node:assert/strict";
import {exportReport,filterReportAlerts,generateReport,parseExportQuery,parseReportQuery,REPORT_TYPES} from "../src/lib/reports/report-engine.mjs";
import {clearReportCache,withReportCache} from "../src/lib/reports/report-cache.mjs";
const NOW="2026-07-25T12:00:00.000Z";
function alert(overrides={}){return{canonicalId:"evt-1",level:"HIGH",ruleId:"R",ruleVersion:"1.0.0",explanation:"Canonical high severity.",evaluatedAt:NOW,sourceEventId:"timeline:event:evt-1",sourceCategory:"earthquake",sourceAttribution:"USGS",canonicalTarget:"/app/events/evt-1",title:"Verified earthquake",providerId:"usgs-earthquakes",providerName:"USGS",priority:"high",location:"Honshu",occurredAt:"2026-07-25T10:00:00.000Z",updatedAt:"2026-07-25T10:30:00.000Z",activity:"active",latitude:35,longitude:139,mapTarget:"/app/map?event=evt-1&focus=1",timelineTarget:"/app/timeline?search=Verified",breakingTarget:"/app/breaking",stale:false,...overrides}}
const filters={type:"daily-global",history:"24h",categories:[],provider:"",risks:[],region:"",search:""};
test("all deterministic report types are registered",()=>assert.deepEqual(REPORT_TYPES.map(x=>x.id),["daily-global","weekly-global","ai-technology","cybersecurity","natural-disaster","space-activity","breaking-news","risk-summary"]));
test("report generation exposes required canonical structure",()=>{const report=generateReport({alerts:[alert()],generatedAt:NOW,degraded:false,stale:false},filters);assert.equal(report.eventCount,1);assert.equal(report.sourceCount,1);assert.deepEqual(report.categories,["earthquake"]);assert.deepEqual(report.canonicalReferences,["/app/events/evt-1"]);assert.equal(report.officialSources[0].attribution[0],"USGS");assert.match(report.reportId,/daily-global/)});
test("sorting and breakdowns are stable",()=>{const report=generateReport({alerts:[alert({canonicalId:"b",sourceEventId:"b",sourceCategory:"space",location:"Orbit",occurredAt:"2026-07-25T11:00:00.000Z"}),alert({canonicalId:"a",sourceEventId:"a"})],generatedAt:NOW,degraded:false,stale:false},{...filters,history:"7d"});assert.deepEqual(report.categoryBreakdown.map(x=>x.category),["earthquake","space"]);assert.equal(report.timeline[0].canonicalId,"b")});
test("filters cover history category provider risk region and search",()=>{const values=[alert(),alert({canonicalId:"old",occurredAt:"2026-07-10T00:00:00.000Z"})];assert.equal(filterReportAlerts(values,{...filters,categories:["earthquake"],provider:"usgs-earthquakes",risks:["HIGH"],region:"hon",search:"verified"},NOW).length,1);assert.equal(filterReportAlerts(values,{...filters,history:"30d"},NOW).length,2)});
test("today history starts at fixed UTC day boundary",()=>{assert.equal(generateReport({alerts:[alert({occurredAt:"2026-07-25T00:00:00.000Z"})],generatedAt:NOW,degraded:false,stale:false},{...filters,history:"today"}).eventCount,1)});
test("exports preserve attribution in markdown JSON and text",()=>{const report=generateReport({alerts:[alert()],generatedAt:NOW,degraded:false,stale:false},filters);for(const format of ["markdown","json","text"])assert.match(exportReport(report,format),/USGS/);assert.match(exportReport(report,"markdown"),/^# Daily Global Report/)});
test("query and export API contracts validate bounded canonical filters",()=>{assert.equal(parseReportQuery(new URLSearchParams("type=space-activity&history=30d&category=space&risk=WATCH")).ok,true);assert.equal(parseReportQuery(new URLSearchParams("type=prediction")).ok,false);assert.equal(parseExportQuery(new URLSearchParams("type=daily-global&format=json")).ok,true);assert.equal(parseExportQuery(new URLSearchParams("format=pdf")).ok,false)});
test("cache is deterministic and serves explicit stale fallback",async()=>{clearReportCache();let calls=0;const loader=async()=>({value:++calls,degraded:false,stale:false});assert.equal((await withReportCache("fixed",10,20,loader,100)).value,1);assert.equal((await withReportCache("fixed",10,20,loader,105)).value,1);const stale=await withReportCache("fixed",10,20,async()=>{throw new Error("offline")},115);assert.equal(stale.stale,true);assert.equal(stale.degraded,true)});
test("API, responsive rendering, and navigation contracts exist",async()=>{const fs=await import("node:fs/promises"),api=await fs.readFile(new URL("../src/app/api/reports/route.ts",import.meta.url),"utf8"),ui=await fs.readFile(new URL("../src/components/reports/ReportsCenter.tsx",import.meta.url),"utf8"),css=await fs.readFile(new URL("../src/app/app/dashboard.css",import.meta.url),"utf8"),mobile=await fs.readFile(new URL("../src/components/mobile/AtlasMobileOverview.tsx",import.meta.url),"utf8");assert.match(api,/REPORTS_UNAVAILABLE/);assert.match(ui,/Export Markdown/);assert.match(css,/@media\(max-width:700px\)/);assert.match(mobile,/href="\/app\/reports"/)});
