import test from "node:test";
import assert from "node:assert/strict";
import {evaluateRiskItem,filterRiskAlerts,generateRiskSnapshot,parseRiskQuery,RISK_RULES,sortRiskAlerts} from "../src/lib/risk/risk-engine.mjs";

const NOW="2026-07-25T12:00:00.000Z";
function item(overrides={}){return{id:"timeline:event:evt-1",itemType:"event",title:"Official event",summary:"Source summary",category:"earthquake",sourceId:"usgs-earthquakes",sourceName:"USGS",sourceUrl:"https://example.test/event",occurredAt:"2026-07-25T10:00:00.000Z",updatedAt:"2026-07-25T10:30:00.000Z",ingestedAt:"2026-07-25T10:31:00.000Z",location:"Honshu",countries:["JP"],coordinates:{latitude:35,longitude:139},severity:"moderate",status:"active",verificationStatus:"verified",attribution:"USGS",stale:false,relatedEventId:"evt-1",relatedReportId:null,metadata:{magnitude:5.8},...overrides}}
const filters={levels:[],categories:[],provider:"",from:null,to:null,activity:"",coordinates:"",search:"",limit:100};

test("classification and precedence are deterministic",()=>{assert.equal(evaluateRiskItem(item({severity:"critical",metadata:{alert:"red"}}),NOW).ruleId,"RISK-OFFICIAL-EXTREME");assert.equal(evaluateRiskItem(item({severity:"critical"}),NOW).level,"CRITICAL");assert.equal(evaluateRiskItem(item({severity:"high"}),NOW).level,"HIGH")});
test("missing fields downgrade safely and explain why",()=>{const result=evaluateRiskItem(item({severity:null,status:"unknown",occurredAt:"2026-07-20T00:00:00.000Z",metadata:{}}),NOW);assert.equal(result.level,"INFORMATIONAL");assert.equal(result.ruleId,"RISK-INFORMATIONAL-FALLBACK");assert.match(result.explanation,/conservatively/)});
test("stable sorting uses level priority timestamp and canonical id",()=>{const a=evaluateRiskItem(item({relatedEventId:"a",id:"a",severity:"high"}),NOW),b=evaluateRiskItem(item({relatedEventId:"b",id:"b",severity:"critical"}),NOW);assert.deepEqual(sortRiskAlerts([a,b]).map(x=>x.canonicalId),["b","a"])});
test("filters cover category level search source coordinates and status",()=>{const alert=evaluateRiskItem(item(),NOW);assert.equal(filterRiskAlerts([alert],{...filters,levels:["ELEVATED"],categories:["earthquake"],provider:"usgs-earthquakes",activity:"active",coordinates:"available",search:"honshu"}).length,1);assert.equal(filterRiskAlerts([alert],{...filters,levels:["CRITICAL"]}).length,0)});
test("snapshot exposes stale degraded state without invented probability",()=>{const snapshot=generateRiskSnapshot({items:[item({stale:true})],providers:[{sourceId:"usgs-earthquakes",sourceName:"USGS",status:"degraded",stale:true}]},NOW);assert.equal(snapshot.degraded,true);assert.equal(snapshot.stale,true);assert.equal(JSON.stringify(snapshot).includes("probability"),false)});
test("rule metadata is public stable and explicit",()=>{assert.ok(RISK_RULES.length>=5);for(const rule of RISK_RULES){assert.equal(rule.ruleVersion,"1.0.0");assert.ok(rule.inputFields.length);assert.ok(rule.explanationTemplate)}});
test("map navigation parameters use canonical event identity",()=>{assert.equal(evaluateRiskItem(item(),NOW).mapTarget,"/app/map?event=evt-1&focus=1");assert.equal(evaluateRiskItem(item({coordinates:null}),NOW).mapTarget,null)});
test("API query contract validates filters",()=>{assert.equal(parseRiskQuery(new URLSearchParams("level=CRITICAL&category=earthquake&activity=active&coordinates=available")).ok,true);assert.equal(parseRiskQuery(new URLSearchParams("level=EXTREME")).ok,false);assert.equal(parseRiskQuery(new URLSearchParams("category=unsupported")).ok,false);assert.equal(parseRiskQuery(new URLSearchParams("probability=90")).ok,false)});
test("API routes and navigation are wired",async()=>{const fs=await import("node:fs/promises"),api=await fs.readFile(new URL("../src/app/api/risk/route.ts",import.meta.url),"utf8"),rules=await fs.readFile(new URL("../src/app/api/risk/rules/route.ts",import.meta.url),"utf8"),side=await fs.readFile(new URL("../src/components/dashboard/AtlasSidebar.tsx",import.meta.url),"utf8"),mobile=await fs.readFile(new URL("../src/components/mobile/AtlasMobileOverview.tsx",import.meta.url),"utf8");assert.match(api,/RISK_UNAVAILABLE/);assert.match(rules,/RISK_RULES/);assert.match(side,/Global Risk/);assert.match(mobile,/href="\/app\/risk"/)});
