import test from "node:test";import assert from "node:assert/strict";
import {buildSearchIndex} from "../src/lib/search/search-index.mjs";import {buildFacets,filterSearchDocuments,parseSearchQuery,searchIndex,suggestFromIndex} from "../src/lib/search/search-engine.mjs";import {searchPath,serializeSearchState} from "../src/lib/search/search-url-state.mjs";import {clearRecentSearches,deleteSavedSearch,loadRecentSearches,loadSavedSearches,recordRecentSearch,renameSavedSearch,saveSearch} from "../src/lib/search/saved-searches.mjs";import {clearSearchCache,withSearchCache} from "../src/lib/search/search-cache.mjs";
const NOW="2026-07-26T12:00:00.000Z";
function alert(overrides={}){return{canonicalId:"evt-1",level:"HIGH",explanation:"Canonical high severity.",sourceEventId:"timeline:event:evt-1",sourceCategory:"earthquake",sourceAttribution:"USGS attribution",canonicalTarget:"/app/events/evt-1",title:"Verified Japan earthquake",providerId:"usgs-earthquakes",providerName:"USGS",priority:"high",location:"Honshu, Japan",occurredAt:"2026-07-26T10:00:00.000Z",updatedAt:"2026-07-26T10:30:00.000Z",latitude:35,longitude:139,mapTarget:"/app/map?event=evt-1&focus=1",timelineTarget:"/app/timeline?search=earthquake",...overrides}}
function index(extra={}){return buildSearchIndex({risk:{alerts:[alert(),...(extra.alerts??[]) ]},breaking:{events:[{canonicalId:"evt-1",providerName:"USGS",providerId:"usgs-earthquakes",sourceUrl:"https://example.test/evt-1",provenance:{attribution:"USGS attribution"}}]},radar:{technologies:[{id:"tech-1",name:"Atlas Model",developer:"Example AI",category:"model",summary:"Official model release",releaseDate:"2026-07-25T00:00:00.000Z",links:[{label:"Model card",url:"https://example.test/model"}],tags:["reasoning"],capabilities:[],provenance:[{providerId:"ai-registry",attribution:"Official registry",sourceUrl:"https://example.test/model"}]}]},reportTypes:[{id:"daily-global",label:"Daily Global Report",defaultHistory:"24h",categories:[],description:"Verified daily report"}],generatedAt:NOW,degradedModules:extra.degradedModules??[]})}
const filters={q:"",categories:[],subcategory:"",provider:"",country:"",region:"",risks:[],timeRange:"",from:null,to:null,contentTypes:[],hasCoordinates:"",hasOfficialSource:"",sort:"newest",page:1,pageSize:25};
test("canonical index normalization merges domains without duplicate identities",()=>{const value=index();assert.equal(value.documents.filter(x=>x.canonicalId==="evt-1").length,1);assert.deepEqual(value.documents.find(x=>x.canonicalId==="evt-1").domains,["timeline-event","risk-alert","map-event","breaking-news"]);assert.equal(value.documents.find(x=>x.canonicalId==="evt-1").officialSourceCount,1)});
test("exact and partial relevance ranking is fixed and explainable",()=>{const value=index();let result=searchIndex(value,{...filters,q:"evt-1",sort:"relevance"});assert.equal(result.results[0].matchReason,"Exact canonical ID match");result=searchIndex(value,{...filters,q:"Verified Japan",sort:"relevance"});assert.equal(result.results[0].matchReason,"Title prefix match");result=searchIndex(value,{...filters,q:"Official model",sort:"relevance"});assert.equal(result.results[0].matchReason,"Description token match")});
test("stable tie breaking uses timestamp then canonical id",()=>{const value=index({alerts:[alert({canonicalId:"evt-0",sourceEventId:"evt-0",title:"Other event"})]});const result=searchIndex(value,{...filters,sort:"newest"});const same=result.results.filter(x=>x.canonicalId.startsWith("evt-"));assert.deepEqual(same.map(x=>x.canonicalId),["evt-0","evt-1"])});
test("combined category provider region risk coordinate source and content filters work",()=>{const value=index(),result=filterSearchDocuments(value.documents,{...filters,categories:["earthquake"],provider:"usgs-earthquakes",region:"honshu",risks:["HIGH"],hasCoordinates:"true",hasOfficialSource:"true",contentTypes:["breaking-news"]},NOW);assert.deepEqual(result.map(x=>x.canonicalId),["evt-1"])});
test("time presets and custom UTC ranges are deterministic",()=>{const value=index();assert.equal(filterSearchDocuments(value.documents,{...filters,timeRange:"today"},NOW).some(x=>x.canonicalId==="evt-1"),true);assert.equal(filterSearchDocuments(value.documents,{...filters,timeRange:"custom",from:"2026-07-25T00:00:00.000Z",to:"2026-07-25T23:59:59.999Z"},NOW).some(x=>x.canonicalId==="tech-1"),true)});
test("all sort modes and pagination are stable",()=>{const value=index();for(const sort of ["newest","oldest","risk-high","risk-low","title","provider","relevance"])assert.ok(searchIndex(value,{...filters,sort,pageSize:1}).results.length===1);const page=searchIndex(value,{...filters,pageSize:1,page:2});assert.equal(page.totalPages,value.documents.length)});
test("facets are contextual and suggestions are stable bounded canonical values",()=>{const value=index(),results=filterSearchDocuments(value.documents,filters,NOW),facets=buildFacets(results);assert.ok(facets.contentTypes.some(x=>x.value==="risk-alert"));assert.deepEqual(suggestFromIndex(value,"us",2).map(x=>x.value),["USGS"]);assert.deepEqual(suggestFromIndex(value,"x"),[])});
test("URL parsing and serialization reproduce canonical state",()=>{const parsed=parseSearchQuery(new URLSearchParams("q=japan&category=earthquake&risk=HIGH&sort=relevance&page=2"));assert.equal(parsed.ok,true);const encoded=serializeSearchState(parsed.filters);assert.match(encoded,/category=earthquake/);assert.equal(searchPath(parsed.filters),`/app/search?${encoded}`);assert.equal(parseSearchQuery(new URLSearchParams("timeRange=custom")).ok,false)});
function storage(initial={}){const map=new Map(Object.entries(initial));return{getItem:key=>map.get(key)??null,setItem:(key,value)=>map.set(key,value),removeItem:key=>map.delete(key)}}
test("saved searches handle create rename load delete duplicate IDs and corruption",()=>{const bad=storage({"atlas.search.saved.v1":"{"});assert.deepEqual(loadSavedSearches(bad),[]);const store=storage(),first=saveSearch(store,{name:"Japan",query:"japan",filters,sort:"relevance"},1),second=saveSearch(store,{name:"Japan",query:"japan",filters,sort:"relevance"},1);assert.notEqual(first.id,second.id);assert.equal(renameSavedSearch(store,first.id,"Japan risk",2),true);assert.equal(loadSavedSearches(store).find(x=>x.id===first.id).name,"Japan risk");assert.equal(deleteSavedSearch(store,first.id),true)});
test("recent history is bounded deduplicated meaningful and clearable",()=>{const store=storage();recordRecentSearch(store,{path:"/app/search?q=a",label:"a",query:"a",createdAt:NOW});recordRecentSearch(store,{path:"/app/search?q=a",label:"a",query:"a",createdAt:NOW});recordRecentSearch(store,{path:"/app/search",label:"empty",query:"",hasFilters:false,createdAt:NOW});assert.equal(loadRecentSearches(store).length,1);clearRecentSearches(store);assert.equal(loadRecentSearches(store).length,0)});
test("cache stale fallback and degraded status never invent documents",async()=>{clearSearchCache();const value=index();await withSearchCache("key",10,20,async()=>value,100);const stale=await withSearchCache("key",10,20,async()=>{throw new Error("offline")},115);assert.equal(stale.documents.length,value.documents.length);assert.ok(stale.status.degradedModules.includes("index-refresh"));const degraded=index({degradedModules:["risk"]});assert.deepEqual(degraded.status.degradedModules,["risk"])});
test("empty results and API/navigation/responsive contracts are present",async()=>{assert.equal(searchIndex(index(),{...filters,q:"not-present"}).totalResults,0);const fs=await import("node:fs/promises"),api=await fs.readFile(new URL("../src/app/api/search/route.ts",import.meta.url),"utf8"),ui=await fs.readFile(new URL("../src/components/search/IntelligenceSearchExplorer.tsx",import.meta.url),"utf8"),mobile=await fs.readFile(new URL("../src/components/mobile/AtlasMobileOverview.tsx",import.meta.url),"utf8"),css=await fs.readFile(new URL("../src/app/app/dashboard.css",import.meta.url),"utf8");assert.match(api,/SEARCH_UNAVAILABLE/);assert.match(ui,/Intelligence Search/);assert.match(mobile,/href="\/app\/search"/);assert.match(css,/@media\(max-width:700px\)/)});
