/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";import {notFound} from "next/navigation";import {getEntity} from "@/lib/graph/entity-graph-service";
export const dynamic="force-dynamic";
export default async function EntityPage({params}:{params:Promise<{entityId:string}>}){const {entityId}=await params,detail=await getEntity(entityId);if(!detail)notFound();const nodes=new Map(detail.connectedNodes.map((x:any)=>[x.nodeId,x]));const relationships=[...detail.incomingRelationships,...detail.outgoingRelationships].sort((a:any,b:any)=>a.edgeId.localeCompare(b.edgeId));const visible=detail.connectedNodes.slice(0,10),radius=135;
  return <main className="entity-detail-page"><nav className="entity-detail-back"><Link href="/app/entities">← All entities</Link><Link href={detail.entity.searchPath}>Search connected intelligence</Link></nav><header><p>ATLAS CANONICAL ENTITY</p><h1>{detail.entity.label}</h1><div><span>{detail.entity.nodeType}</span><span>{detail.entity.entityType}</span><code>{detail.entity.canonicalId}</code></div></header>{detail.degraded?<div className="entities-degraded" role="status">{detail.warnings.join(" ")}</div>:null}
    <section className="entity-detail-summary"><article><span>Relationships</span><strong>{relationships.length}</strong></article><article><span>Connected records</span><strong>{detail.entity.connectedRecordCount}</strong></article><article><span>Highest existing risk</span><strong>{detail.entity.aggregateRisk??"Not classified"}</strong></article><article><span>Official sources</span><strong>{detail.officialSources.length}</strong></article></section>
    <section className="entity-visual"><header><h2>Relationship explorer</h2><p>Stable placement; every line has canonical evidence. The table below is the accessible fallback.</p></header><svg viewBox="0 0 420 360" role="img" aria-label={`Relationship graph for ${detail.entity.label}`}><circle cx="210" cy="180" r="48"/><text x="210" y="180">{detail.entity.label.slice(0,22)}</text>{visible.map((node:any,index:number)=>{const angle=(index/Math.max(visible.length,1))*Math.PI*2-Math.PI/2,x=210+Math.cos(angle)*radius,y=180+Math.sin(angle)*radius;return <g key={node.nodeId}><line x1="210" y1="180" x2={x} y2={y}/><circle cx={x} cy={y} r="32"/><text x={x} y={y}>{node.label.slice(0,14)}</text></g>})}</svg></section>
    <section className="entity-detail-grid">{detail.relatedEvents.length?<article><h2>Related events</h2>{detail.relatedEvents.map((x:any)=><Link key={x.nodeId} href={x.canonicalPath}>{x.label}</Link>)}</article>:null}{detail.relatedReports.length?<article><h2>Related reports</h2>{detail.relatedReports.map((x:any)=><Link key={x.nodeId} href={x.canonicalPath}>{x.label}</Link>)}</article>:null}{detail.relatedRiskAlerts.length?<article><h2>Risk alerts</h2>{detail.relatedRiskAlerts.map((x:any)=><Link key={x.nodeId} href={x.canonicalPath}>{x.label}</Link>)}</article>:null}{detail.officialSources.length?<article><h2>Official sources</h2>{detail.officialSources.map((x:any)=><a key={x.nodeId} href={x.canonicalPath} target="_blank" rel="noopener noreferrer">{x.label} · {x.provenance.map((p:any)=>p.attribution).join("; ")}</a>)}</article>:null}{detail.mapReferences.length?<article><h2>Map references</h2>{detail.mapReferences.map((x:any)=><Link key={x.nodeId} href={x.mapPath}>{x.label}</Link>)}</article>:null}</section>
    <section className="entity-relations"><h2>Evidence-backed relationships</h2><div className="entity-table-wrap"><table><thead><tr><th>Direction</th><th>Relationship</th><th>Connected node</th><th>Evidence</th><th>Policy</th></tr></thead><tbody>{relationships.map((edge:any)=>{const incoming=edge.targetNodeId===entityId,node=nodes.get(incoming?edge.sourceNodeId:edge.targetNodeId) as any;return <tr key={edge.edgeId}><td>{incoming?"Incoming":"Outgoing"}</td><td>{edge.relationshipType}</td><td>{node?.label}</td><td><Link href={edge.evidencePath}>{edge.evidenceCanonicalId}</Link></td><td>{edge.confidencePolicy}</td></tr>})}</tbody></table></div></section>
    <section className="entity-provenance"><h2>Provenance</h2>{detail.provenance.map((x:any,index:number)=><p key={`${x.providerId}:${index}`}><strong>{x.providerId}</strong> · {x.attribution}{x.sourceUrl?<> · <a href={x.sourceUrl}>Official source</a></>:null}</p>)}</section></main>}
