"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
const TYPES=["entity","country","organization","category","provider","risk-level","search-query","location"];
export function WatchlistsCenter(){
 const [data,setData]=useState<any>(null),[selected,setSelected]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[name,setName]=useState(""),[type,setType]=useState("search-query"),[value,setValue]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{const response=await fetch("/api/watchlists",{cache:"no-store"}),json=await response.json();if(!response.ok&&response.status!==206)throw new Error();setData(json);setError("")}catch{setError("Watchlists are unavailable. No replacement intelligence was generated.")}finally{setLoading(false)}},[]);
 useEffect(()=>{queueMicrotask(load)},[load]);
 async function create(event:any){event.preventDefault();if(!name.trim()||!value.trim())return;const response=await fetch("/api/watchlists",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,target:{type,value}})});if(response.ok){setName("");setValue("");load()}}
 async function toggle(item:any){await fetch(`/api/watchlists/${encodeURIComponent(item.id)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({enabled:!item.enabled})});load()}
 async function rename(item:any){const next=window.prompt("Rename watchlist",item.name)?.trim();if(next){await fetch(`/api/watchlists/${encodeURIComponent(item.id)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({name:next})});load()}}
 async function remove(item:any){if(window.confirm(`Delete ${item.name}?`)){await fetch(`/api/watchlists/${encodeURIComponent(item.id)}`,{method:"DELETE"});if(selected?.watchlist.id===item.id)setSelected(null);load()}}
 async function detail(item:any){const response=await fetch(`/api/watchlists/${encodeURIComponent(item.id)}`,{cache:"no-store"});if(response.ok)setSelected(await response.json())}
 return <main className="watchlists-page"><header className="watchlists-hero"><div><p>ATLAS LOCAL MONITORING</p><h1>Watchlists</h1><span>Deterministic monitoring of verified canonical intelligence</span></div><nav><Link href="/app/search">Search</Link><Link href="/app/risk">Global Risk</Link></nav></header>
 {data?.status?.degraded?<div className="watchlists-degraded" role="status">{data.status.warnings.join(" ")}</div>:null}{error?<div className="watchlists-error" role="alert">{error}</div>:null}
 <section className="watchlists-summary" aria-label="Watchlist status"><article><span>Watchlists</span><strong>{data?.summary.totalWatchlists??0}</strong></article><article><span>Enabled</span><strong>{data?.summary.enabledWatchlists??0}</strong></article><article><span>New alerts</span><strong>{data?.summary.newAlerts??0}</strong></article><article><span>Matches</span><strong>{data?.summary.totalAlerts??0}</strong></article><article><span>Latest match</span><strong>{data?.summary.latestMatchAt?new Date(data.summary.latestMatchAt).toLocaleString():"None"}</strong></article></section>
 <section className="watchlists-layout"><div><form className="watchlist-create" onSubmit={create}><h2>Create watchlist</h2><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Japan monitoring"/></label><label>Target type<select value={type} onChange={e=>setType(e.target.value)}>{TYPES.map(item=><option key={item}>{item}</option>)}</select></label><label>Verified value<input value={value} onChange={e=>setValue(e.target.value)} placeholder="country, provider, category, or query"/></label><button type="submit">Create watchlist</button></form>
<div className="watchlist-list"><header><h2>Your watchlists</h2><span aria-live="polite">{loading?"Loading…":`${data?.watchlists.length??0} local lists`}</span></header>{data?.watchlists?.length?data.watchlists.map((item:any)=><article key={item.id} className={!item.enabled?"disabled":""}><button className="watchlist-open" type="button" onClick={()=>detail(item)}><strong>{item.name}</strong><span>{item.target.type}: {item.target.value}</span><small>{item.enabled?"Enabled":"Disabled"} · {item.totalMatchCount} total matches{item.lastMatchAt?` · last ${new Date(item.lastMatchAt).toLocaleString()}`:""}</small></button><footer><button type="button" onClick={()=>toggle(item)}>{item.enabled?"Disable":"Enable"}</button><button type="button" onClick={()=>rename(item)}>Rename</button><button type="button" onClick={()=>remove(item)}>Delete</button></footer></article>):<div className="watchlists-empty">No local watchlists yet. Add a canonical target to begin monitoring.</div>}</div></div>
 <aside className="watchlist-alerts"><header><h2>Alert history</h2><Link href="/api/watchlists/alerts">API</Link></header>{data?.alerts?.length?data.alerts.slice(0,12).map((alert:any)=><article key={alert.id}><span className={`alert-status ${alert.status.toLowerCase()}`}>{alert.status}</span><Link href={alert.document.canonicalPath}>{alert.document.title}</Link><small>{alert.matchingReason} · {new Date(alert.timestamp).toLocaleString()}</small><button type="button" onClick={async()=>{await fetch("/api/watchlists/alerts",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({alertId:alert.id,status:alert.status==="NEW"?"READ":"DISMISSED"})});load()}}>{alert.status==="NEW"?"Mark read":"Dismiss"}</button></article>):<p className="watchlists-empty">No matching canonical events yet.</p>}</aside></section>
 {selected?<div className="watchlist-dialog" role="dialog" aria-modal="true" aria-label={`${selected.watchlist.name} detail`}><button type="button" onClick={()=>setSelected(null)}>Close</button><h2>{selected.watchlist.name}</h2><p>{selected.watchlist.target.type}: {selected.watchlist.target.value}</p><h3>Recent matches</h3>{selected.matches.length?selected.matches.map((alert:any)=><Link key={alert.id} href={alert.document.canonicalPath}>{alert.document.title} · {alert.matchingReason}</Link>):<p>No matches.</p>}</div>:null}</main>;
}
