export type AtlasDataSourceStatus = "active" | "disabled" | "planned" | "unavailable" | "configuration_required";
export type AtlasDataSource = {
  id: string; name: string; organization: string;
  category: "earthquake" | "weather" | "cyclone" | "news" | "space" | "health" | "air-quality" | "aviation";
  status: AtlasDataSourceStatus; documentationUrl: string;
  endpoints: Readonly<Record<string, string>>; requiresApiKey: boolean;
  environmentVariable?: string; attribution: string; licenseOrTermsUrl?: string;
  refreshSeconds: number; enabledByDefault: boolean; notes?: string;
};

export const DATA_SOURCES = [
  { id: "usgs-earthquakes", name: "USGS Earthquake Hazards Program", organization: "U.S. Geological Survey", category: "earthquake", status: "active", documentationUrl: "https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php", endpoints: { "24h": "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson", "7d": "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_week.geojson", "30d": "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_month.geojson" }, requiresApiKey: false, attribution: "Earthquake data courtesy of the U.S. Geological Survey", licenseOrTermsUrl: "https://www.usgs.gov/information-policies-and-instructions/copyrights-and-credits", refreshSeconds: 60, enabledByDefault: true },
  { id: "open-meteo", name: "Open-Meteo Forecast API", organization: "Open-Meteo", category: "weather", status: "active", documentationUrl: "https://open-meteo.com/en/docs", endpoints: { forecast: "https://api.open-meteo.com/v1/forecast", customerForecast: "https://customer-api.open-meteo.com/v1/forecast", geocoding: "https://geocoding-api.open-meteo.com/v1/search" }, requiresApiKey: false, attribution: "Weather data by Open-Meteo.com (CC BY 4.0)", licenseOrTermsUrl: "https://open-meteo.com/en/terms", refreshSeconds: 900, enabledByDefault: true, notes: "Runtime-disabled unless OPEN_METEO_API_KEY is set for commercial access or OPEN_METEO_ALLOW_NONCOMMERCIAL=true explicitly confirms eligible free-tier use." },
  { id: "reliefweb", name: "ReliefWeb API v2", organization: "UN OCHA", category: "news", status: "configuration_required", documentationUrl: "https://apidoc.reliefweb.int/", endpoints: { reports: "https://api.reliefweb.int/v2/reports", disasters: "https://api.reliefweb.int/v2/disasters" }, requiresApiKey: false, environmentVariable: "RELIEFWEB_APPNAME_APPROVED", attribution: "ReliefWeb / UN OCHA and the named original information partner", licenseOrTermsUrl: "https://apidoc.reliefweb.int/", refreshSeconds: 1800, enabledByDefault: false, notes: "ReliefWeb returned HTTP 403 for atlas.chela-x.space on 2026-07-23. Register and obtain approval for this exact appname, then set RELIEFWEB_APPNAME_APPROVED=true." },
  { id: "nasa-rss", name: "NASA Official RSS", organization: "National Aeronautics and Space Administration", category: "space", status: "active", documentationUrl: "https://www.nasa.gov/rss-feeds/", endpoints: { releases: "https://www.nasa.gov/news-release/feed/", recent: "https://www.nasa.gov/feed/", technology: "https://www.nasa.gov/technology/feed/" }, requiresApiKey: false, attribution: "National Aeronautics and Space Administration (NASA)", licenseOrTermsUrl: "https://www.nasa.gov/nasa-brand-center/images-and-media/", refreshSeconds: 900, enabledByDefault: true, notes: "Metadata and short feed excerpts only; no article bodies or media are mirrored." },
  { id: "esa-rss", name: "ESA Official RSS", organization: "European Space Agency", category: "space", status: "active", documentationUrl: "https://www.esa.int/rssfeed/Our_Activities", endpoints: { activities: "https://www.esa.int/rssfeed/Our_Activities" }, requiresApiKey: false, attribution: "European Space Agency (ESA)", licenseOrTermsUrl: "https://www.esa.int/Services/Terms_and_conditions", refreshSeconds: 1800, enabledByDefault: true, notes: "Metadata and short feed excerpts only; ESA article text and media are not republished." },
  { id: "jpl-news", name: "JPL News", organization: "NASA Jet Propulsion Laboratory", category: "space", status: "disabled", documentationUrl: "https://www.jpl.nasa.gov/rss/", endpoints: { feed: "https://www.jpl.nasa.gov/feeds/news/" }, requiresApiKey: false, attribution: "NASA/JPL", licenseOrTermsUrl: "https://www.nasa.gov/nasa-brand-center/images-and-media/", refreshSeconds: 900, enabledByDefault: false, notes: "Temporarily disabled: the official feed returned HTTP 403 to the production-style server fetch test on 2026-07-22." },
  { id: "cneos-news", name: "CNEOS News", organization: "NASA/JPL Center for Near Earth Object Studies", category: "space", status: "disabled", documentationUrl: "https://cneos.jpl.nasa.gov/", endpoints: { feed: "https://cneos.jpl.nasa.gov/feed/news.xml" }, requiresApiKey: false, attribution: "NASA/JPL CNEOS", licenseOrTermsUrl: "https://www.nasa.gov/nasa-brand-center/images-and-media/", refreshSeconds: 1800, enabledByDefault: false, notes: "Temporarily quarantined with the NASA/JPL news integration until live items and public detail links can be verified end to end." },
  { id: "noaa-nhc", name: "NHC/CPHC Tropical Cyclones", organization: "NOAA National Hurricane Center", category: "cyclone", status: "active", documentationUrl: "https://www.nhc.noaa.gov/aboutrss.shtml", endpoints: { atlantic: "https://www.nhc.noaa.gov/gis-at.xml", easternPacific: "https://www.nhc.noaa.gov/gis-ep.xml", centralPacific: "https://www.nhc.noaa.gov/gis-cp.xml" }, requiresApiKey: false, attribution: "NOAA/National Hurricane Center", licenseOrTermsUrl: "https://www.weather.gov/disclaimer", refreshSeconds: 300, enabledByDefault: true, notes: "Experimental GIS feeds; not for life-threatening decisions." },
  { id: "who-emergencies", name: "WHO Disease Outbreak News", organization: "World Health Organization", category: "health", status: "planned", documentationUrl: "https://www.who.int/api/emergencies/diseaseoutbreaknews/sfhelp", endpoints: {}, requiresApiKey: false, attribution: "World Health Organization", licenseOrTermsUrl: "https://www.who.int/about/policies/publishing/copyright", refreshSeconds: 3600, enabledByDefault: false, notes: "An official Sitefinity API is documented, but its stable query/pagination contract has not yet been validated for ATLAS." },
  { id: "openaq-v3", name: "OpenAQ API v3", organization: "OpenAQ", category: "air-quality", status: "disabled", documentationUrl: "https://docs.openaq.org/api", endpoints: { api: "https://api.openaq.org/v3" }, requiresApiKey: true, environmentVariable: "OPENAQ_API_KEY", attribution: "OpenAQ", licenseOrTermsUrl: "https://docs.openaq.org/about/terms", refreshSeconds: 900, enabledByDefault: false, notes: "Disabled until a v3 X-API-Key is configured." },
  { id: "opensky", name: "OpenSky Network API", organization: "The OpenSky Network", category: "aviation", status: "disabled", documentationUrl: "https://openskynetwork.github.io/opensky-api/index.html", endpoints: { api: "https://opensky-network.org/api" }, requiresApiKey: true, environmentVariable: "OPENSKY_CLIENT_ID", attribution: "The OpenSky Network", licenseOrTermsUrl: "https://opensky-network.org/about/terms-of-use", refreshSeconds: 30, enabledByDefault: false, notes: "Disabled pending OAuth2 credentials and confirmation that usage terms fit deployment." },
] as const satisfies readonly AtlasDataSource[];

export function getDataSource(id: string): AtlasDataSource | undefined { return DATA_SOURCES.find((source) => source.id === id); }
export function getDataSourceDisabledReason(source: AtlasDataSource): string | undefined {
  if (source.status !== "active" || !source.enabledByDefault) return source.notes ?? "Integration disabled";
  if (source.id === "open-meteo" && !process.env.OPEN_METEO_API_KEY && process.env.OPEN_METEO_ALLOW_NONCOMMERCIAL !== "true") return "Open-Meteo disabled: configure a commercial API key or explicitly confirm eligible non-commercial usage";
  return undefined;
}
export function getActiveDataSource(id: string): AtlasDataSource {
  const source = getDataSource(id);
  if (!source) throw new Error(`Data source ${id} is not configured`);
  const disabledReason = getDataSourceDisabledReason(source);
  if (disabledReason) throw new Error(disabledReason);
  return source;
}
export function isDataSourceFetchable(source: AtlasDataSource): boolean {
  return getDataSourceDisabledReason(source) === undefined && Object.keys(source.endpoints).length > 0;
}
