/* eslint-disable @typescript-eslint/no-explicit-any */
import {getBreakingSnapshot} from "@/lib/breaking/breaking-service";
import {aggregateTimeline} from "@/lib/timeline/timeline-service";
import {getRiskSnapshot} from "@/lib/risk/risk-service";
import {getWatchlistSnapshot} from "@/lib/watchlists/watchlist-service";
import {getReport} from "@/lib/reports/report-service";
import {filterAlerts,summarizeAlerts,deduplicateAlerts,normalizeAlert} from "./alert-engine.mjs";
import {statusFor,transition,auditFor} from "./alert-store.mjs";
import type {Alert,AlertFilters,AlertStatus} from "./alert-contracts";
const prioritySeverity=(priority:string)=>priority==="critical"?"CRITICAL":priority==="high"?"HIGH":priority==="medium"?"ELEVATED":"INFORMATIONAL";
function provenance(providerId:string,attribution:string,sourceUrl:string|null,producer:string,sourceRecordId:string){return[{providerId,attribution,sourceUrl,producer,sourceRecordId}]}
function base(input:any):Alert{return normalizeAlert({...input,status:statusFor(input.alertId),updatedAt:input.updatedAt??input.createdAt})}
function fromRisk(items:any[]):Alert[]{return items.map(item=>base({alertId:`risk:${item.canonicalId}`,source:"risk",sourceRecordId:item.canonicalId,severity:item.level,priority:item.priority,status:"NEW",canonicalReference:{canonicalId:item.canonicalId,path:item.canonicalTarget,type:"event"},matchingReason:item.explanation,title:item.title,category:item.sourceCategory,riskLevel:item.level,createdAt:item.evaluatedAt,occurredAt:item.occurredAt,provenance:provenance(item.providerId,item.sourceAttribution,null,"risk",item.canonicalId),metadata:{ruleId:item.ruleId,ruleVersion:item.ruleVersion,stale:item.stale}}))}
function fromBreaking(items:any[]):Alert[]{return items.map(item=>base({alertId:`breaking:${item.canonicalId}`,source:"breaking",sourceRecordId:item.canonicalId,severity:prioritySeverity(item.priority),priority:item.priority,status:"NEW",canonicalReference:{canonicalId:item.canonicalId,path:item.eventDetailUrl??item.timelineUrl,type:"event"},matchingReason:`Breaking News priority: ${item.priority}`,title:item.title,category:item.category,riskLevel:null,createdAt:item.publishedAt,occurredAt:item.publishedAt,provenance:provenance(item.providerId,item.provenance.attribution,item.sourceUrl,"breaking",item.canonicalId),metadata:{verified:item.verified}}))}
function fromTimeline(items:any[]):Alert[]{return items.filter(item=>["high","critical"].includes(item.severity)).map(item=>base({alertId:`timeline:${item.id}`,source:"timeline",sourceRecordId:item.id,severity:item.severity==="critical"?"CRITICAL":"HIGH",priority:item.severity==="critical"?"critical":"high",status:"NEW",canonicalReference:{canonicalId:item.id,path:`/app/events/${encodeURIComponent(item.id)}`,type:item.itemType},matchingReason:`Canonical Timeline severity: ${item.severity}`,title:item.title,category:item.category,riskLevel:null,createdAt:item.updatedAt,occurredAt:item.occurredAt,provenance:provenance(item.sourceId,item.attribution,item.sourceUrl??null,"timeline",item.id),metadata:{verificationStatus:item.verificationStatus}}))}
function fromWatchlists(items:any[]):Alert[]{return items.map(item=>base({alertId:`watchlists:${item.id}`,source:"watchlists",sourceRecordId:item.id,severity:item.document.riskLevel??"INFORMATIONAL",priority:item.document.riskLevel==="CRITICAL"?"critical":item.document.riskLevel==="HIGH"?"high":"information",status:item.status,canonicalReference:{canonicalId:item.document.canonicalId,path:item.document.canonicalPath,type:item.document.contentType},matchingReason:item.matchingReason,title:item.document.title,category:item.document.category,riskLevel:item.document.riskLevel,createdAt:item.timestamp,occurredAt:item.timestamp,provenance:item.document.provenance.map((p:any)=>({providerId:p.providerId,attribution:p.attribution,sourceUrl:p.sourceUrl,producer:"watchlists",sourceRecordId:item.document.canonicalId})),metadata:{watchlistId:item.watchlistId}}))}
function fromReport(report:any):Alert[]{if(!report?.report?.eventCount)return[];const value=report.report;return[base({alertId:`reports:${value.reportType}`,source:"reports",sourceRecordId:value.reportId,severity:"INFORMATIONAL",priority:"information",status:"NEW",canonicalReference:{canonicalId:value.reportId,path:`/app/reports?type=${encodeURIComponent(value.reportType)}`,type:"report"},matchingReason:`Report generated from ${value.eventCount} canonical events`,title:value.title,category:null,riskLevel:null,createdAt:value.generatedAt,occurredAt:value.generatedAt,provenance:value.providers.flatMap((p:any)=>p.attribution.map((attribution:string)=>({providerId:p.id,attribution,sourceUrl:null,producer:"reports",sourceRecordId:value.reportId}))),metadata:{reportType:value.reportType,eventCount:value.eventCount}})]}
export async function getAlertSnapshot(){const results=await Promise.allSettled([aggregateTimeline(),getBreakingSnapshot(),getRiskSnapshot(),getWatchlistSnapshot(),getReport({type:"daily-global",history:"24h",categories:[],provider:"",risks:[],region:"",search:""})]);const warnings:string[]=[];const value=(index:number,name:string):any=>{const result=results[index];if(result.status==="rejected"){warnings.push(name);return null}return result.value};const timeline=value(0,"timeline"),breaking=value(1,"breaking"),risk=value(2,"risk"),watchlists=value(3,"watchlists"),reports=value(4,"reports");const alerts=deduplicateAlerts([...fromTimeline(timeline?.items??[]),...fromBreaking(breaking?.events??[]),...fromRisk(risk?.alerts??[]),...fromWatchlists(watchlists?.alerts??[]),...fromReport(reports)]);const generatedAt=new Date().toISOString();return{alerts,generatedAt,warnings,degraded:warnings.length>0,summary:summarizeAlerts(alerts,generatedAt,warnings)}}
export async function listAlerts(filters:AlertFilters){const snapshot=await getAlertSnapshot(),filtered=filterAlerts(snapshot.alerts,filters),start=(filters.page-1)*filters.pageSize;return{alerts:filtered.slice(start,start+filters.pageSize),total:filtered.length,totalPages:Math.ceil(filtered.length/filters.pageSize),page:filters.page,pageSize:filters.pageSize,filters,generatedAt:snapshot.generatedAt,degraded:snapshot.degraded,warnings:snapshot.warnings,summary:snapshot.summary}}
export async function getAlert(id:string){const snapshot=await getAlertSnapshot(),alert=snapshot.alerts.find(item=>item.alertId===id);return alert?{alert,audit:auditFor(id),generatedAt:snapshot.generatedAt,degraded:snapshot.degraded,warnings:snapshot.warnings}:null}
export async function transitionAlert(id:string,status:AlertStatus){const current=await getAlert(id);if(!current)return null;transition(id,status,new Date().toISOString(),"Alert Center lifecycle transition");return getAlert(id)}
