export const ALERT_STATUSES=Object.freeze(["CREATED","NEW","ACKNOWLEDGED","READ","DISMISSED","ARCHIVED"]);
export const ALERT_SOURCES=Object.freeze(["timeline","breaking","risk","watchlists","reports"]);
const SEVERITY={CRITICAL:0,HIGH:1,ELEVATED:2,WATCH:3,INFORMATIONAL:4};
const TRANSITIONS={CREATED:["NEW"],NEW:["ACKNOWLEDGED","READ","DISMISSED"],ACKNOWLEDGED:["READ","DISMISSED"],READ:["DISMISSED","ARCHIVED"],DISMISSED:["ARCHIVED"],ARCHIVED:[]};
export function canTransition(from,to){return from===to||Boolean(TRANSITIONS[from]?.includes(to))}
export function severityForPriority(priority){return priority==="critical"?"CRITICAL":priority==="high"?"HIGH":priority==="medium"?"ELEVATED":"INFORMATIONAL"}
export function normalizeAlert(input){return{...input,status:ALERT_STATUSES.includes(input.status)?input.status:"NEW",severity:input.severity??"INFORMATIONAL",priority:input.priority??"information",category:input.category??null,riskLevel:input.riskLevel??null}}
export function deduplicateAlerts(alerts){const values=new Map();for(const alert of alerts){const current=values.get(alert.alertId);if(!current||Date.parse(alert.updatedAt)>Date.parse(current.updatedAt))values.set(alert.alertId,alert)}return[...values.values()].sort((a,b)=>a.alertId.localeCompare(b.alertId))}
export function filterAlerts(alerts,filters){const from=filters.from?Date.parse(filters.from):null,to=filters.to?Date.parse(filters.to):null,query=String(filters.search??"").trim().toLocaleLowerCase("en-US");return alerts.filter(alert=>(!filters.statuses.length||filters.statuses.includes(alert.status))&&(!filters.severities.length||filters.severities.includes(alert.severity))&&(!filters.sources.length||filters.sources.includes(alert.source))&&(!filters.categories.length||(alert.category&&filters.categories.includes(alert.category)))&&(!filters.riskLevels.length||(alert.riskLevel&&filters.riskLevels.includes(alert.riskLevel)))&&(!from||Date.parse(alert.occurredAt)>=from)&&(!to||Date.parse(alert.occurredAt)<=to)&&(!query||[alert.alertId,alert.title,alert.source,alert.sourceRecordId,alert.category??"",alert.matchingReason].join(" ").toLocaleLowerCase("en-US").includes(query))).sort((a,b)=>filters.sort==="oldest"?Date.parse(a.occurredAt)-Date.parse(b.occurredAt)||a.alertId.localeCompare(b.alertId):filters.sort==="severity"?(SEVERITY[a.severity]??9)-(SEVERITY[b.severity]??9)||Date.parse(b.occurredAt)-Date.parse(a.occurredAt)||a.alertId.localeCompare(b.alertId):filters.sort==="source"?a.source.localeCompare(b.source)||Date.parse(b.occurredAt)-Date.parse(a.occurredAt)||a.alertId.localeCompare(b.alertId):Date.parse(b.occurredAt)-Date.parse(a.occurredAt)||a.alertId.localeCompare(b.alertId))}
export function summarizeAlerts(alerts,generatedAt,warnings=[]){const statusCounts=Object.fromEntries(ALERT_STATUSES.map(x=>[x,0])),severityCounts=Object.fromEntries(Object.keys(SEVERITY).map(x=>[x,0])),sourceCounts=Object.fromEntries(["timeline","breaking","risk","watchlists","reports"].map(x=>[x,0]));for(const alert of alerts){statusCounts[alert.status]++;severityCounts[alert.severity]++;sourceCounts[alert.source]++}return{total:alerts.length,statusCounts,severityCounts,sourceCounts,latestActivityAt:[...alerts].sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt))[0]?.updatedAt??null,degraded:warnings.length>0,warnings,generatedAt}}
export function parseAlertQuery(params){const allowed=new Set(["status","severity","source","category","risk","from","to","search","sort","page","pageSize"]);for(const key of params.keys())if(!allowed.has(key))return{ok:false,code:"INVALID_PARAMETERS",message:`Unsupported parameter: ${key}`};const list=key=>[...new Set((params.get(key)??"").split(",").map(x=>x.trim()).filter(Boolean))],statuses=list("status"),severities=list("severity"),sources=list("source"),page=Number(params.get("page")??1),pageSize=Number(params.get("pageSize")??25),sort=params.get("sort")??"newest",from=params.get("from"),to=params.get("to");if(statuses.some(x=>!ALERT_STATUSES.includes(x))||severities.some(x=>!Object.keys(SEVERITY).includes(x))||sources.some(x=>!ALERT_SOURCES.includes(x))||!['newest','oldest','severity','source'].includes(sort)||!Number.isInteger(page)||page<1||!Number.isInteger(pageSize)||pageSize<1||pageSize>100||(from&&!Number.isFinite(Date.parse(from)))||(to&&!Number.isFinite(Date.parse(to)))||(from&&to&&Date.parse(from)>Date.parse(to)))return{ok:false,code:"INVALID_PARAMETERS",message:"Alert filters are invalid"};return{ok:true,filters:{statuses,severities,sources,categories:list("category"),riskLevels:list("risk"),from,to,search:params.get("search")??"",sort,page,pageSize}}}
