"use client";
import Link from "next/link";
import { useMemo,useState } from "react";
import type { CapabilityId,RadarSnapshot,Technology } from "@/lib/ai-radar/ai-radar-contract";
const CAPABILITIES=["reasoning","coding","vision","speech","image","video","embeddings","rag","tool-calling","agents","function-calling","structured-output"] as CapabilityId[];
function TechCard({item}:{item:Technology}){
  return <article className="ai-tech-card"><header><div><span>{item.category}</span><h3>{item.name}</h3><p>{item.developer}</p></div><b>{item.status}</b></header><p>{item.summary}</p><dl><div><dt>License</dt><dd>{item.license??"Not published"}</dd></div><div><dt>Release</dt><dd>{item.releaseDate??"Not published"}</dd></div><div><dt>Context</dt><dd>{item.contextWindow?.toLocaleString()??"Not published"}</dd></div><div><dt>Local</dt><dd>{item.localDeployment.status}</dd></div><div><dt>Open source</dt><dd>{item.openSource?"Yes":"No"}</dd></div><div><dt>Commercial</dt><dd>{item.commercial?"Yes":"No"}</dd></div><div><dt>API</dt><dd>{item.apiAvailable?"Available":"Not published"}</dd></div><div><dt>Open weights</dt><dd>{item.openWeights?"Yes":"No"}</dd></div></dl><div className="ai-tags">{item.tags.map(tag=><span key={tag}>{tag}</span>)}</div><footer>{item.links.map(link=><a key={`${link.type}:${link.url}`} href={link.url} target="_blank" rel="noopener noreferrer">{link.label} ↗</a>)}</footer></article>;
}
export function AiRadarExplorer({snapshot}:{snapshot:RadarSnapshot}){
  const [search,setSearch]=useState(""),[category,setCategory]=useState("all"),[openOnly,setOpenOnly]=useState(false),[apiOnly,setApiOnly]=useState(false),[localOnly,setLocalOnly]=useState(false),[capability,setCapability]=useState("all");
  const items=useMemo(()=>snapshot.technologies.filter(item=>{
    const q=search.trim().toLowerCase();
    return (!q||[item.name,item.developer,item.summary,...item.tags].join(" ").toLowerCase().includes(q))&&(category==="all"||item.category===category)&&(!openOnly||item.openSource)&&(!apiOnly||item.apiAvailable)&&(!localOnly||item.localDeployment.status==="supported")&&(capability==="all"||item.capabilities.some(entry=>entry.id===capability&&entry.supported));
  }),[snapshot,search,category,openOnly,apiOnly,localOnly,capability]);
  const releases=snapshot.releases.slice(0,12),benchmarks=snapshot.benchmarks.slice(0,12);
  return <main className="ai-radar-page">
    <nav className="event-detail-back"><Link href="/app">← Global Overview</Link><a href="#directory">Directory</a><a href="#benchmarks">Benchmarks</a></nav>
    <header className="ai-radar-hero"><div><p>ATLAS AI TECHNOLOGY RADAR V1</p><h1>Verified AI technology intelligence.</h1><span>Official releases, project documentation, deployment facts, and version-specific benchmark records. No generated rankings.</span></div><dl><div><dt>Technologies</dt><dd>{snapshot.technologies.length}</dd></div><div><dt>Live releases</dt><dd>{snapshot.releases.length}</dd></div><div><dt>Benchmark records</dt><dd>{snapshot.benchmarks.length}</dd></div><div><dt>Generated</dt><dd>{new Date(snapshot.generatedAt).toLocaleString()}</dd></div></dl></header>
    {snapshot.partial&&<aside className="ai-radar-partial"><strong>{snapshot.stale?"Stale snapshot · not live":"Partial provider coverage"}</strong><span>Responding official sources remain visible. Missing releases or scores are not estimated.</span></aside>}
    <section className="ai-radar-section"><div className="ai-radar-heading"><span>OFFICIAL RELEASE ENDPOINTS</span><h2>Latest AI releases</h2></div>{releases.length?<div className="ai-release-grid">{releases.map(item=><article key={item.id}><span>{item.category}</span><h3>{item.name}</h3><p>{item.company} · <time dateTime={item.releaseDate}>{new Date(item.releaseDate).toLocaleDateString()}</time></p><small>{item.version}</small><p>{item.summary}</p><div>{item.links.map(link=><a key={link.url} href={link.url} target="_blank" rel="noopener noreferrer">Official release ↗</a>)}</div></article>)}</div>:<p className="ai-empty">Official release providers are unavailable. No dates or releases were substituted.</p>}</section>
    <section className="ai-radar-section" id="directory"><div className="ai-radar-heading"><span>VERIFIED DIRECTORY</span><h2>AI directory</h2></div><div className="ai-search"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search technologies, companies, tags…" aria-label="Search AI directory"/><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{[...new Set(snapshot.technologies.map(item=>item.category))].map(value=><option key={value}>{value}</option>)}</select><select value={capability} onChange={e=>setCapability(e.target.value)}><option value="all">All capabilities</option>{CAPABILITIES.map(value=><option key={value}>{value}</option>)}</select><label><input type="checkbox" checked={openOnly} onChange={e=>setOpenOnly(e.target.checked)}/> Open source</label><label><input type="checkbox" checked={apiOnly} onChange={e=>setApiOnly(e.target.checked)}/> API</label><label><input type="checkbox" checked={localOnly} onChange={e=>setLocalOnly(e.target.checked)}/> Local</label></div><p className="ai-result-count">{items.length} verified technologies</p><div className="ai-tech-grid">{items.map(item=><TechCard item={item} key={item.id}/>)}</div></section>
    <section className="ai-radar-section" id="benchmarks"><div className="ai-radar-heading"><span>VERSION-PRESERVED RESULTS</span><h2>Benchmarks</h2></div>{benchmarks.length?<div className="ai-benchmark-table"><table><thead><tr><th>Technology / system</th><th>Benchmark</th><th>Score</th><th>Evaluation</th><th>Configuration</th><th>Source</th></tr></thead><tbody>{benchmarks.map(item=><tr key={item.id}><td>{item.technologyName}</td><td>{item.benchmark} · {item.benchmarkVersion}</td><td>{item.score.toFixed(2)}%</td><td>{item.evaluationDate}</td><td>{item.testConfiguration}</td><td><a href={item.officialSourceUrl} target="_blank" rel="noopener noreferrer">Official ↗</a></td></tr>)}</tbody></table></div>:<p className="ai-empty">The official benchmark provider is unavailable. No benchmark scores are shown.</p>}</section>
    <section className="ai-radar-section"><div className="ai-radar-heading"><span>VERIFIED DESTINATIONS</span><h2>Try now</h2></div><div className="ai-try-grid">{snapshot.technologies.map(item=><article key={item.id}><h3>{item.name}</h3><p>{item.developer}</p><div>{item.links.map(link=><a key={link.url} href={link.url} target="_blank" rel="noopener noreferrer">{link.label} ↗</a>)}</div></article>)}</div></section>
    <section className="ai-radar-section"><div className="ai-radar-heading"><span>DOCUMENTED SUPPORT ONLY</span><h2>Feature matrix</h2></div><div className="ai-feature-table"><table><thead><tr><th>Technology</th>{CAPABILITIES.map(id=><th key={id}>{id}</th>)}<th>Open weights</th><th>API</th><th>Local</th></tr></thead><tbody>{snapshot.technologies.map(item=><tr key={item.id}><td>{item.name}</td>{CAPABILITIES.map(id=><td key={id}>{item.capabilities.find(cap=>cap.id===id)?.supported?"●":"—"}</td>)}<td>{item.openWeights?"●":"—"}</td><td>{item.apiAvailable?"●":"—"}</td><td>{item.localDeployment.status==="supported"?"●":item.localDeployment.status==="experimental"?"◐":"—"}</td></tr>)}</tbody></table></div></section>
    <section className="ai-radar-section"><div className="ai-radar-heading"><span>LOCAL DEPLOYMENT</span><h2>Verified runtimes and requirements</h2></div><div className="ai-deploy-grid">{snapshot.technologies.filter(item=>item.localDeployment.status!=="not-supported").map(item=><article key={item.id}><h3>{item.name}</h3><strong>{item.localDeployment.status}</strong><p>{item.localDeployment.runtimes.join(" · ")||"Runtime not published"}</p><dl><div><dt>RAM</dt><dd>{item.localDeployment.ramGb??"Not published"}</dd></div><div><dt>VRAM</dt><dd>{item.localDeployment.vramGb??"Not published"}</dd></div><div><dt>GPU</dt><dd>{item.localDeployment.gpu??"Not published"}</dd></div><div><dt>Quantization</dt><dd>{item.localDeployment.quantization.join(", ")||"Not published"}</dd></div></dl></article>)}</div></section>
    <section className="ai-radar-section"><div className="ai-radar-heading"><span>NEWEST FIRST · OFFICIAL TIMESTAMPS</span><h2>Release timeline</h2></div>{releases.length?<ol className="ai-release-timeline">{releases.map(item=><li key={item.id}><time dateTime={item.releaseDate}>{new Date(item.releaseDate).toLocaleDateString()}</time><div><h3>{item.name}</h3><p>{item.company} · {item.category} · {item.version}</p></div>{item.links.map(link=><a key={link.url} href={link.url} target="_blank" rel="noopener noreferrer">Official ↗</a>)}</li>)}</ol>:<p className="ai-empty">No verified releases are currently available.</p>}</section>
    <section className="ai-radar-method"><h2>Provenance and limitations</h2><p>Every technology, capability, deployment state, release, score, and link retains its official source. Unknown requirements remain “Not published.” Benchmarks are never combined across versions and ATLAS does not generate rankings.</p><div>{snapshot.providers.map(provider=><span key={provider.id}>{provider.name}: <b>{provider.state}</b> · {provider.itemCount} records</span>)}</div><p>Architecture reference: docs/ATLAS-AI-RADAR.md</p></section>
  </main>
}
