"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect, react-hooks/preserve-manual-memoization */
import Link from "next/link";import {useCallback,useEffect,useMemo,useState} from "react";import {parseEntityQuery,ENTITY_NODE_TYPES,ENTITY_TYPES} from "@/lib/graph/entity-graph-query.mjs";import {serializeEntityState} from "@/lib/graph/entity-url-state.mjs";
const DEFAULT={q:"",entityTypes:[],nodeTypes:[],categories:[],country:"",region:"",provider:"",risks:[],relationshipType:"",direction:"",page:1,pageSize:25,sort:"label-asc"};
function toggle(values:string[],value:string){return values.includes(value)?values.filter(x=>x!==value):[...values,value]}
export function EntityKnowledgeGraph(){
  const [filters,setFilters]=useState<any>(DEFAULT),[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[ready,setReady]=useState(false),[open,setOpen]=useState(false);
  useEffect(()=>{const parsed=parseEntityQuery(new URLSearchParams(window.location.search));if(parsed.ok)setFilters(parsed.filters);setReady(true)},[]);
  const query=useMemo(()=>serializeEntityState(filters),[filters]),load=useCallback(async()=>{if(!ready)return;setLoading(true);try{const response=await fetch(`/api/entities?${query}`,{cache:"no-store"}),value=await response.json();if(!response.ok&&response.status!==206)throw new Error();setData(value);setError("")}catch{setError("Canonical entity graph is unavailable. No replacement entities are shown.")}finally{setLoading(false)}},[query,ready]);
  useEffect(()=>{if(!ready)return;window.history.replaceState(null,"",query?`/app/entities?${query}`:"/app/entities");queueMicrotask(load)},[query,ready,load]);
  const update=(patch:any)=>setFilters((value:any)=>({...value,...patch,page:patch.page??1}));
  return <main className="entities-page"><header className="entities-hero"><div><p>ATLAS EVIDENCE GRAPH</p><h1>Entity Knowledge Graph</h1><span>Canonical entities and explicit relationships only</span></div><nav><Link href="/app/search">Search</Link><Link href="/api/graph/status">Graph Status</Link></nav></header>
    {data?.degraded?<div className="entities-degraded" role="status">{data.warnings.join(" ")}</div>:null}{error?<div className="entities-error" role="alert">{error}</div>:null}
    <form className="entities-search" onSubmit={e=>e.preventDefault()}><label><span className="sr-only">Search entities</span><input type="search" value={filters.q} onChange={e=>update({q:e.target.value})} placeholder="Search explicit entity label or canonical ID"/></label><label>Sort<select value={filters.sort} onChange={e=>update({sort:e.target.value})}>{["label-asc","label-desc","most-connected","most-recent","highest-risk","official-sources"].map(x=><option key={x}>{x}</option>)}</select></label><button type="button" onClick={()=>setFilters(DEFAULT)}>Clear</button></form>
    <div className="entities-mobile-filter"><button type="button" onClick={()=>setOpen(x=>!x)} aria-expanded={open} aria-controls="entity-filters">Filters</button></div>
    <section className="entities-layout"><aside id="entity-filters" className={`entity-filters ${open?"open":""}`}><h2>Entity filters</h2><fieldset><legend>Entity type</legend>{ENTITY_TYPES.map(x=><label key={x}><input type="checkbox" checked={filters.entityTypes.includes(x)} onChange={()=>update({entityTypes:toggle(filters.entityTypes,x)})}/><span>{x}</span></label>)}</fieldset><fieldset><legend>Node type</legend>{ENTITY_NODE_TYPES.filter(x=>["ENTITY","LOCATION","ORGANIZATION","PROVIDER","CATEGORY"].includes(x)).map(x=><label key={x}><input type="checkbox" checked={filters.nodeTypes.includes(x)} onChange={()=>update({nodeTypes:toggle(filters.nodeTypes,x)})}/><span>{x}</span></label>)}</fieldset><label>Category<input value={filters.categories.join(",")} onChange={e=>update({categories:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/></label><label>Country<select value={filters.country} onChange={e=>update({country:e.target.value})}><option value="">All countries</option>{(data?.facets.countries??[]).map((x:any)=><option key={x.value}>{x.value}</option>)}</select></label><label>Region<select value={filters.region} onChange={e=>update({region:e.target.value})}><option value="">All regions</option>{(data?.facets.regions??[]).map((x:any)=><option key={x.value}>{x.value}</option>)}</select></label><label>Provider<select value={filters.provider} onChange={e=>update({provider:e.target.value})}><option value="">All providers</option>{(data?.facets.providers??[]).map((x:any)=><option key={x.value}>{x.value}</option>)}</select></label><label>Risk<input value={filters.risks.join(",")} onChange={e=>update({risks:e.target.value.toUpperCase().split(",").map(x=>x.trim()).filter(Boolean)})}/></label></aside>
      <div className="entity-results"><header aria-live="polite"><strong>{loading?"Building graph…":`${data?.totalEntities??0} entities`}</strong><span>{data?`${data.graphStatus.nodeCount} nodes · ${data.graphStatus.edgeCount} evidence edges`:""}</span></header>{data?.entities?.length?data.entities.map((entity:any)=><article key={entity.nodeId}><header><span>{entity.nodeType}</span><b>{entity.entityType}</b>{entity.aggregateRisk?<b>{entity.aggregateRisk}</b>:null}</header><h2><Link href={`/app/entities/${encodeURIComponent(entity.nodeId)}`}>{entity.label}</Link></h2><code>{entity.canonicalId}</code><dl><div><dt>Relationships</dt><dd>{entity.relationshipCount}</dd></div><div><dt>Connected records</dt><dd>{entity.connectedRecordCount}</dd></div><div><dt>Official sources</dt><dd>{entity.connectedOfficialSourceCount}</dd></div><div><dt>Coordinates</dt><dd>{entity.latitude!==null&&entity.longitude!==null?"Verified":"Unavailable"}</dd></div></dl><footer><Link href={`/app/entities/${encodeURIComponent(entity.nodeId)}`}>Explore entity</Link><Link href={entity.searchPath}>Search records</Link>{entity.mapPath?<Link href={entity.mapPath}>Open Map</Link>:null}</footer></article>):!loading?<div className="entities-empty">No verified entities match the current filters.</div>:null}{data?.totalPages>1?<nav className="entity-pages"><button disabled={filters.page<=1} onClick={()=>update({page:filters.page-1})}>Previous</button><span>Page {filters.page} of {data.totalPages}</span><button disabled={filters.page>=data.totalPages} onClick={()=>update({page:filters.page+1})}>Next</button></nav>:null}</div>
    </section></main>
}
