function unique(values){return[...new Set(values.filter(Boolean))]}
function riskDoc(alert){
  const official=alert.sourceAttribution?[{title:alert.providerName,url:""}]:[];
  return{searchDocumentId:`search:${alert.canonicalId}`,canonicalId:alert.canonicalId,contentType:"timeline-event",domains:["timeline-event","risk-alert",...(alert.mapTarget?["map-event"]:[])],title:alert.title,description:alert.explanation,category:alert.sourceCategory,subcategory:null,provider:alert.providerId,sourceOrganization:alert.providerName,country:null,region:alert.location,city:null,locationLabel:alert.location,riskLevel:alert.level,occurredAt:alert.occurredAt,publishedAt:alert.occurredAt,updatedAt:alert.updatedAt,latitude:alert.latitude,longitude:alert.longitude,officialSourceCount:official.length,officialSources:official,tags:[alert.sourceCategory,alert.level],canonicalPath:alert.canonicalTarget,mapPath:alert.mapTarget,reportPath:null,riskPath:`/app/risk?search=${encodeURIComponent(alert.canonicalId)}`,timelinePath:alert.timelineTarget,provenance:[{providerId:alert.providerId,attribution:alert.sourceAttribution,sourceUrl:null}]};
}
function aiDoc(item){
  const links=item.links??[],provenance=item.provenance??[];
  return{searchDocumentId:`search:${item.id}`,canonicalId:item.id,contentType:"ai-radar",domains:["ai-radar"],title:item.name,description:item.summary,category:"ai",subcategory:item.category??null,provider:item.developer,sourceOrganization:item.developer,country:null,region:null,city:null,locationLabel:null,riskLevel:null,occurredAt:item.releaseDate??item.provenance?.[0]?.retrievedAt,publishedAt:item.releaseDate??item.provenance?.[0]?.retrievedAt,updatedAt:item.releaseDate??item.provenance?.[0]?.retrievedAt,latitude:null,longitude:null,officialSourceCount:links.length,officialSources:links.map(link=>({title:link.label,url:link.url})),tags:unique([...(item.tags??[]),...(item.capabilities??[]).filter(x=>x.supported).map(x=>x.id)]),canonicalPath:`/app/ai?search=${encodeURIComponent(item.name)}`,mapPath:null,reportPath:null,riskPath:null,timelinePath:null,provenance:provenance.map(x=>({providerId:x.providerId,attribution:x.attribution,sourceUrl:x.sourceUrl}))};
}
function reportDoc(type,generatedAt){
  return{searchDocumentId:`search:report:${type.id}`,canonicalId:`report:${type.id}`,contentType:"report",domains:["report"],title:type.label,description:type.description,category:type.categories[0]??null,subcategory:type.id,provider:"atlas-reports",sourceOrganization:"ATLAS Reports Center",country:null,region:null,city:null,locationLabel:null,riskLevel:null,occurredAt:generatedAt,publishedAt:generatedAt,updatedAt:generatedAt,latitude:null,longitude:null,officialSourceCount:0,officialSources:[],tags:[type.id,...type.categories],canonicalPath:`/app/reports?type=${encodeURIComponent(type.id)}&history=${encodeURIComponent(type.defaultHistory)}`,mapPath:null,reportPath:`/app/reports?type=${encodeURIComponent(type.id)}&history=${encodeURIComponent(type.defaultHistory)}`,riskPath:null,timelinePath:null,provenance:[{providerId:"atlas-reports",attribution:"ATLAS verified canonical data aggregation",sourceUrl:null}]};
}
function merge(left,right){return{...left,domains:unique([...left.domains,...right.domains]),officialSources:[...new Map([...left.officialSources,...right.officialSources].map(x=>[`${x.title}:${x.url}`,x])).values()],officialSourceCount:new Set([...left.officialSources,...right.officialSources].map(x=>`${x.title}:${x.url}`)).size,provenance:[...new Map([...left.provenance,...right.provenance].map(x=>[`${x.providerId}:${x.attribution}:${x.sourceUrl}`,x])).values()]}}
export function buildSearchIndex(input){
  const byId=new Map();
  for(const alert of input.risk?.alerts??[])byId.set(alert.canonicalId,riskDoc(alert));
  for(const event of input.breaking?.events??[]){const current=byId.get(event.canonicalId);if(current)byId.set(event.canonicalId,{...current,domains:unique([...current.domains,"breaking-news"]),country:current.country??event.country,region:current.region??event.region,locationLabel:current.locationLabel??event.region??event.country,officialSources:[{title:event.providerName,url:event.sourceUrl}],officialSourceCount:1,provenance:[{providerId:event.providerId,attribution:event.provenance.attribution,sourceUrl:event.sourceUrl}]});}
  for(const item of input.radar?.technologies??[]){const doc=aiDoc(item),current=byId.get(doc.canonicalId);byId.set(doc.canonicalId,current?merge(current,doc):doc)}
  for(const type of input.reportTypes??[]){const doc=reportDoc(type,input.generatedAt);byId.set(doc.canonicalId,doc)}
  const documents=[...byId.values()].filter(x=>x.title&&Number.isFinite(Date.parse(x.occurredAt))).sort((a,b)=>Date.parse(b.occurredAt)-Date.parse(a.occurredAt)||a.canonicalId.localeCompare(b.canonicalId));
  const degradedModules=[...input.degradedModules].sort(),warnings=degradedModules.map(name=>`${name} unavailable; index contains verified results from available modules only.`);
  return{documents,status:{ready:documents.length>0,documentCount:documents.length,contentTypesIndexed:unique(documents.flatMap(x=>x.domains)).sort(),generatedAt:input.generatedAt,degradedModules,warnings}};
}
