import {BREAKING_CATEGORIES} from "../breaking/breaking-logic.mjs";
import {RISK_LEVELS} from "../risk/risk-engine.mjs";
export const SEARCH_SORTS=Object.freeze(["newest","oldest","risk-high","risk-low","title","provider","relevance"]);
export const SEARCH_CONTENT_TYPES=Object.freeze(["timeline-event","breaking-news","risk-alert","report","ai-radar","map-event"]);
const RISK_ORDER={CRITICAL:0,HIGH:1,ELEVATED:2,WATCH:3,INFORMATIONAL:4};
function normalized(value){return String(value??"").toLowerCase().normalize("NFKC").replace(/[^\p{L}\p{N}:/.-]+/gu," ").trim()}
function rank(document,query){
  const q=normalized(query);if(!q)return{score:0,reason:"No search text; ordered by selected sort."};
  const title=normalized(document.title),id=normalized(document.canonicalId),provider=normalized(`${document.provider} ${document.sourceOrganization}`),location=normalized(`${document.country??""} ${document.region??""} ${document.city??""} ${document.locationLabel??""}`),category=normalized(`${document.category??""} ${document.subcategory??""}`),description=normalized(`${document.description} ${document.tags.join(" ")} ${document.officialSources.map(x=>`${x.title} ${x.url}`).join(" ")}`);
  if(id===q)return{score:800,reason:"Exact canonical ID match"};if(title===q)return{score:700,reason:"Exact title match"};if(title.startsWith(q))return{score:600,reason:"Title prefix match"};
  const tokens=q.split(" ").filter(Boolean);if(tokens.every(x=>title.includes(x)))return{score:500,reason:"Title token match"};if(provider.includes(q))return{score:400,reason:"Provider match"};if(location.includes(q))return{score:300,reason:"Location match"};if(category.includes(q))return{score:200,reason:"Category match"};if(tokens.every(x=>description.includes(x)))return{score:100,reason:"Description token match"};return{score:-1,reason:"No match"};
}
function timeBoundary(filters,generatedAt){const to=filters.timeRange==="custom"&&filters.to?Date.parse(filters.to):Date.parse(generatedAt);if(filters.timeRange==="today"){const d=new Date(to);return{from:Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()),to}}if(["24h","7d","30d"].includes(filters.timeRange))return{from:to-({24:1,"24h":1,"7d":7,"30d":30}[filters.timeRange])*86_400_000,to};return{from:filters.timeRange==="custom"&&filters.from?Date.parse(filters.from):null,to:filters.timeRange==="custom"?to:null}}
export function filterSearchDocuments(documents,filters,generatedAt){
  const times=timeBoundary(filters,generatedAt),country=normalized(filters.country),region=normalized(filters.region),subcategory=normalized(filters.subcategory);
  return documents.map(document=>({document,match:rank(document,filters.q)})).filter(({document,match})=>match.score>=0&&(!filters.categories.length||(document.category&&filters.categories.includes(document.category)))&&(!subcategory||normalized(document.subcategory).includes(subcategory))&&(!filters.provider||document.provider===filters.provider)&&(!country||normalized(document.country).includes(country))&&(!region||normalized(`${document.region??""} ${document.locationLabel??""}`).includes(region))&&(!filters.risks.length||(document.riskLevel&&filters.risks.includes(document.riskLevel)))&&(!filters.contentTypes.length||filters.contentTypes.some(x=>document.domains.includes(x)))&&(!filters.hasCoordinates||(filters.hasCoordinates==="true"?(document.latitude!==null&&document.longitude!==null):(document.latitude===null||document.longitude===null)))&&(!filters.hasOfficialSource||(filters.hasOfficialSource==="true"?document.officialSourceCount>0:document.officialSourceCount===0))&&(times.from===null||Date.parse(document.occurredAt)>=times.from)&&(times.to===null||Date.parse(document.occurredAt)<=times.to)).map(({document,match})=>({...document,relevanceRank:match.score,matchReason:match.reason}));
}
function stable(results,sort){const risk=x=>x.riskLevel?RISK_ORDER[x.riskLevel]:5,stableId=(a,b)=>a.canonicalId.localeCompare(b.canonicalId),newest=(a,b)=>Date.parse(b.occurredAt)-Date.parse(a.occurredAt)||stableId(a,b);return[...results].sort((a,b)=>sort==="oldest"?Date.parse(a.occurredAt)-Date.parse(b.occurredAt)||stableId(a,b):sort==="risk-high"?risk(a)-risk(b)||newest(a,b):sort==="risk-low"?risk(b)-risk(a)||newest(a,b):sort==="title"?a.title.localeCompare(b.title)||newest(a,b):sort==="provider"?a.provider.localeCompare(b.provider)||newest(a,b):sort==="relevance"?b.relevanceRank-a.relevanceRank||newest(a,b):newest(a,b))}
function facet(results,getter){const counts=new Map();for(const result of results)for(const value of getter(result))if(value)counts.set(value,(counts.get(value)??0)+1);return[...counts].map(([value,count])=>({value,count})).sort((a,b)=>b.count-a.count||a.value.localeCompare(b.value))}
export function buildFacets(results){return{categories:facet(results,x=>[x.category]),contentTypes:facet(results,x=>x.domains),providers:facet(results,x=>[x.provider]),countries:facet(results,x=>[x.country]),regions:facet(results,x=>[x.region]),riskLevels:facet(results,x=>[x.riskLevel])}}
export function searchIndex(index,filters){
  const filtered=filterSearchDocuments(index.documents,filters,index.status.generatedAt),facets=buildFacets(filtered),ordered=stable(filtered,filters.sort),totalResults=ordered.length,totalPages=Math.ceil(totalResults/filters.pageSize),start=(filters.page-1)*filters.pageSize;
  return{query:filters.q,filters,sort:filters.sort,page:filters.page,pageSize:filters.pageSize,totalResults,totalPages,results:ordered.slice(start,start+filters.pageSize),facets};
}
export function suggestFromIndex(index,q,limit=8){const query=normalized(q);if(query.length<2)return[];const values=[];for(const x of index.documents)values.push({type:"title",value:x.title,path:x.canonicalPath},{type:"provider",value:x.sourceOrganization,path:null},{type:"canonical-id",value:x.canonicalId,path:x.canonicalPath},...(x.country?[{type:"country",value:x.country,path:null}]:[]),...(x.region?[{type:"region",value:x.region,path:null}]:[]),...(x.category?[{type:"category",value:x.category,path:null}]:[]));return[...new Map(values.filter(x=>normalized(x.value).includes(query)).map(x=>[`${x.type}:${normalized(x.value)}`,x])).values()].sort((a,b)=>(normalized(a.value).startsWith(query)?-1:0)-(normalized(b.value).startsWith(query)?-1:0)||a.value.localeCompare(b.value)||a.type.localeCompare(b.type)).slice(0,Math.max(1,Math.min(limit,20)))}
const PARAMS=new Set(["q","category","subcategory","provider","country","region","risk","timeRange","from","to","contentType","hasCoordinates","hasOfficialSource","sort","page","pageSize"]);
export function parseSearchQuery(params){for(const key of params.keys())if(!PARAMS.has(key))return{ok:false,code:"INVALID_PARAMETERS",message:`Unsupported parameter: ${key}`};const list=key=>[...new Set((params.get(key)??"").split(",").map(x=>x.trim()).filter(Boolean))],categories=list("category"),risks=list("risk"),contentTypes=list("contentType"),timeRange=params.get("timeRange")??"",sort=params.get("sort")??(params.get("q")?"relevance":"newest"),page=Number(params.get("page")??1),pageSize=Number(params.get("pageSize")??25),q=params.get("q")??"",from=params.get("from"),to=params.get("to"),hasCoordinates=params.get("hasCoordinates")??"",hasOfficialSource=params.get("hasOfficialSource")??"";if(q.length>200||categories.some(x=>!BREAKING_CATEGORIES.includes(x))||risks.some(x=>!RISK_LEVELS.includes(x))||contentTypes.some(x=>!SEARCH_CONTENT_TYPES.includes(x))||!["","today","24h","7d","30d","custom"].includes(timeRange)||!SEARCH_SORTS.includes(sort)||!["","true","false"].includes(hasCoordinates)||!["","true","false"].includes(hasOfficialSource)||!Number.isInteger(page)||page<1||!Number.isInteger(pageSize)||pageSize<1||pageSize>100||(timeRange==="custom"&&(!from||!to||!Number.isFinite(Date.parse(from))||!Number.isFinite(Date.parse(to))||Date.parse(from)>Date.parse(to))))return{ok:false,code:"INVALID_PARAMETERS",message:"Search filters are invalid"};return{ok:true,filters:{q,categories,subcategory:params.get("subcategory")??"",provider:params.get("provider")??"",country:params.get("country")??"",region:params.get("region")??"",risks,timeRange,from,to,contentTypes,hasCoordinates,hasOfficialSource,sort,page,pageSize}}}
