"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
import Link from "next/link";import {useCallback,useEffect,useMemo,useState} from "react";
import type {SearchFilters,SearchResponse} from "@/lib/search/search-contracts";
import {parseSearchQuery,SEARCH_CONTENT_TYPES,SEARCH_SORTS} from "@/lib/search/search-engine.mjs";
import {clearRecentSearches,deleteSavedSearch,loadRecentSearches,loadSavedSearches,recordRecentSearch,renameSavedSearch,saveSearch} from "@/lib/search/saved-searches.mjs";
import {searchPath,serializeSearchState} from "@/lib/search/search-url-state.mjs";
const DEFAULT:SearchFilters={q:"",categories:[],subcategory:"",provider:"",country:"",region:"",risks:[],timeRange:"",from:null,to:null,contentTypes:[],hasCoordinates:"",hasOfficialSource:"",sort:"newest",page:1,pageSize:25};
const CATEGORY_LABELS:Record<string,string>={earthquake:"Earthquake",volcano:"Volcano","weather":"Weather & Climate",disaster:"Disasters",conflict:"Conflict",economy:"Economy & Markets",ai:"AI & Technology",cyber:"Cybersecurity",aviation:"Aviation (Flights)",marine:"Marine (Ships)",space:"Space & Satellites",energy:"Energy",health:"Health & Disease"};
function csvToggle(values:readonly string[],value:string){return values.includes(value)?values.filter(x=>x!==value):[...values,value]}
export function IntelligenceSearchExplorer(){
  const [filters,setFilters]=useState<SearchFilters>(DEFAULT),[data,setData]=useState<SearchResponse|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[initialized,setInitialized]=useState(false),[suggestions,setSuggestions]=useState<{type:string;value:string;path:string|null}[]>([]),[filtersOpen,setFiltersOpen]=useState(false),[saveName,setSaveName]=useState(""),[saved,setSaved]=useState<any[]>([]),[recent,setRecent]=useState<any[]>([]);
  useEffect(()=>{const parsed=parseSearchQuery(new URLSearchParams(window.location.search));if(parsed.ok)setFilters(parsed.filters);try{setSaved(loadSavedSearches(window.localStorage));setRecent(loadRecentSearches(window.localStorage))}catch{}setInitialized(true)},[]);
  const query=useMemo(()=>serializeSearchState(filters),[filters]);
  const load=useCallback(async()=>{if(!initialized)return;setLoading(true);try{const response=await fetch(`/api/search?${query}`,{cache:"no-store"}),value=await response.json() as SearchResponse&{error?:{message?:string}};if(!response.ok&&response.status!==206)throw new Error(value.error?.message);setData(value);setError("")}catch{setError("Canonical search is unavailable. No replacement results are shown.")}finally{setLoading(false)}},[initialized,query]);
  useEffect(()=>{if(!initialized)return;window.history.replaceState(null,"",searchPath(filters));queueMicrotask(load)},[filters,initialized,load]);
  useEffect(()=>{if(!initialized||filters.q.trim().length<2){setSuggestions([]);return}let cancelled=false;const timer=window.setTimeout(()=>fetch(`/api/search/suggestions?q=${encodeURIComponent(filters.q)}&limit=8`).then(x=>x.json()).then(x=>{if(!cancelled)setSuggestions(x.suggestions??[])}).catch(()=>{}),180);return()=>{cancelled=true;window.clearTimeout(timer)}},[filters.q,initialized]);
  function update(patch:Partial<SearchFilters>){setFilters(value=>({...value,...patch,page:patch.page??1}))}
  function submit(){try{const path=searchPath(filters),items=recordRecentSearch(window.localStorage,{path,label:filters.q||"Filtered search",query:filters.q,hasFilters:query.replace(/(^|&)q=[^&]*/,"").length>0,createdAt:new Date().toISOString()});setRecent(items)}catch{}}
  function save(){try{const item=saveSearch(window.localStorage,{name:saveName,query:filters.q,filters,sort:filters.sort},Date.now());if(item){setSaved(loadSavedSearches(window.localStorage));setSaveName("")}}catch{}}
  function loadSaved(item:any){setFilters({...DEFAULT,...item.filters,q:item.query,sort:item.sort,page:1})}
  const active=[...filters.categories.map(x=>({key:`category:${x}`,label:CATEGORY_LABELS[x]??x,clear:()=>update({categories:filters.categories.filter(y=>y!==x)})})),...filters.risks.map(x=>({key:`risk:${x}`,label:x,clear:()=>update({risks:filters.risks.filter(y=>y!==x)})})),...filters.contentTypes.map(x=>({key:`type:${x}`,label:x,clear:()=>update({contentTypes:filters.contentTypes.filter(y=>y!==x)})})),...["provider","country","region","subcategory","timeRange","hasCoordinates","hasOfficialSource"].filter(key=>Boolean((filters as any)[key])).map(key=>({key,label:`${key}: ${(filters as any)[key]}`,clear:()=>update({[key]:""} as Partial<SearchFilters>)}))];
  const providers=data?.facets.providers??[],countries=data?.facets.countries??[],regions=data?.facets.regions??[];
  return <main className="search-page">
    <header className="search-hero"><div><p>ATLAS CANONICAL DISCOVERY</p><h1>Intelligence Search &amp; Explorer</h1><span>Deterministic search across verified ATLAS intelligence</span></div><Link href="/api/search/status">Index Status</Link></header>
    <form className="search-bar" onSubmit={e=>{e.preventDefault();submit()}} role="search"><label><span className="sr-only">Search verified intelligence</span><input type="search" value={filters.q} onChange={e=>update({q:e.target.value,sort:e.target.value?"relevance":"newest"})} placeholder="Search titles, canonical IDs, providers, locations, categories…"/></label><button type="submit">Search</button><button type="button" onClick={()=>setFilters(DEFAULT)}>Clear all</button>{suggestions.length?<ul aria-label="Deterministic search suggestions">{suggestions.map(item=><li key={`${item.type}:${item.value}`}><button type="button" onClick={()=>update({q:item.value,sort:"relevance"})}><small>{item.type}</small>{item.value}</button></li>)}</ul>:null}</form>
    {data?.degraded?<div className="search-degraded" role="status">{data.warnings.join(" ")}</div>:null}{error?<div className="search-error" role="alert">{error}</div>:null}
    <div className="search-mobile-tools"><button type="button" onClick={()=>setFiltersOpen(x=>!x)} aria-expanded={filtersOpen} aria-controls="search-filters">Filters ({active.length})</button></div>
    <section className="search-layout">
      <aside id="search-filters" className={`search-filters ${filtersOpen?"open":""}`} aria-label="Search filters"><h2>Filters</h2>
        <fieldset><legend>Category</legend>{(data?.facets.categories??[]).map(item=><label key={item.value}><input type="checkbox" checked={filters.categories.includes(item.value as any)} onChange={()=>update({categories:csvToggle(filters.categories,item.value) as any})}/><span>{CATEGORY_LABELS[item.value]??item.value}</span><b>{item.count}</b></label>)}</fieldset>
        <label>Subcategory<input value={filters.subcategory} onChange={e=>update({subcategory:e.target.value})}/></label><label>Provider<select value={filters.provider} onChange={e=>update({provider:e.target.value})}><option value="">All providers</option>{providers.map(x=><option key={x.value}>{x.value}</option>)}</select></label><label>Country<select value={filters.country} onChange={e=>update({country:e.target.value})}><option value="">All countries</option>{countries.map(x=><option key={x.value}>{x.value}</option>)}</select></label><label>Region<select value={filters.region} onChange={e=>update({region:e.target.value})}><option value="">All regions</option>{regions.map(x=><option key={x.value}>{x.value}</option>)}</select></label>
        <fieldset><legend>Risk level</legend>{["CRITICAL","HIGH","ELEVATED","WATCH","INFORMATIONAL"].map(x=><label key={x}><input type="checkbox" checked={filters.risks.includes(x as any)} onChange={()=>update({risks:csvToggle(filters.risks,x) as any})}/><span>{x}</span></label>)}</fieldset>
        <label>Time range<select value={filters.timeRange} onChange={e=>update({timeRange:e.target.value as any,from:null,to:null})}><option value="">All time</option><option value="today">Today · UTC</option><option value="24h">Last 24 Hours</option><option value="7d">Last 7 Days</option><option value="30d">Last 30 Days</option><option value="custom">Custom Range</option></select></label>{filters.timeRange==="custom"?<><label>From · UTC<input type="datetime-local" value={filters.from?.slice(0,16)??""} onChange={e=>update({from:e.target.value?new Date(`${e.target.value}:00Z`).toISOString():null})}/></label><label>To · UTC<input type="datetime-local" value={filters.to?.slice(0,16)??""} onChange={e=>update({to:e.target.value?new Date(`${e.target.value}:00Z`).toISOString():null})}/></label></>:null}
        <fieldset><legend>Content type</legend>{SEARCH_CONTENT_TYPES.map(x=><label key={x}><input type="checkbox" checked={filters.contentTypes.includes(x as any)} onChange={()=>update({contentTypes:csvToggle(filters.contentTypes,x) as any})}/><span>{x}</span></label>)}</fieldset><label>Coordinates<select value={filters.hasCoordinates} onChange={e=>update({hasCoordinates:e.target.value as any})}><option value="">Any</option><option value="true">Available</option><option value="false">Unavailable</option></select></label><label>Official source<select value={filters.hasOfficialSource} onChange={e=>update({hasOfficialSource:e.target.value as any})}><option value="">Any</option><option value="true">Available</option><option value="false">Unavailable</option></select></label>
      </aside>
      <div className="search-results">
        <header><div aria-live="polite"><strong>{loading?"Searching…":`${data?.totalResults??0} results`}</strong><span>{data?`Index generated ${new Date(data.generatedAt).toLocaleString()}`:""}</span></div><label>Sort<select value={filters.sort} onChange={e=>update({sort:e.target.value as any})}>{SEARCH_SORTS.map(x=><option value={x} key={x}>{x.replace("-"," ")}</option>)}</select></label></header>
        {active.length?<div className="search-chips" aria-label="Active filters">{active.map(item=><button type="button" key={item.key} onClick={item.clear}>{item.label} ×</button>)}</div>:null}
        {data?.results.length?data.results.map(result=><article className="search-result" key={result.searchDocumentId}><header><span>{result.contentType}</span>{result.category?<b>{CATEGORY_LABELS[result.category]??result.category}</b>:null}{result.riskLevel?<b>{result.riskLevel}</b>:null}<time>{new Date(result.occurredAt).toLocaleString()}</time></header><h2><Link href={result.canonicalPath}>{result.title}</Link></h2><p>{result.description}</p><dl><div><dt>Provider</dt><dd>{result.sourceOrganization}</dd></div><div><dt>Location</dt><dd>{result.locationLabel??"Not supplied"}</dd></div><div><dt>Sources</dt><dd>{result.officialSourceCount}</dd></div><div><dt>Match</dt><dd>{result.matchReason}</dd></div></dl><footer><span>Verified provenance · {result.provenance.map(x=>x.attribution).join("; ")}</span><nav><Link href={result.canonicalPath}>Open</Link>{result.timelinePath?<Link href={result.timelinePath}>Timeline</Link>:null}{result.mapPath?<Link href={result.mapPath}>Map</Link>:null}{result.riskPath?<Link href={result.riskPath}>Risk</Link>:null}{result.reportPath?<Link href={result.reportPath}>Report</Link>:null}{result.officialSources.find(x=>x.url)?<a href={result.officialSources.find(x=>x.url)!.url} target="_blank" rel="noopener noreferrer">Source</a>:null}</nav></footer></article>):!loading?<div className="search-empty"><h2>No verified results</h2><p>Adjust filters or clear the search. Empty categories are not filled with substitute data.</p></div>:null}
        {data&&data.totalPages>1?<nav className="search-pages" aria-label="Search result pages"><button type="button" disabled={filters.page<=1} onClick={()=>update({page:filters.page-1})}>Previous</button><span>Page {filters.page} of {data.totalPages}</span><button type="button" disabled={filters.page>=data.totalPages} onClick={()=>update({page:filters.page+1})}>Next</button></nav>:null}
      </div>
      <aside className="search-local"><section><h2>Saved searches</h2><label>Name<input value={saveName} onChange={e=>setSaveName(e.target.value)} placeholder="Search name"/></label><button type="button" onClick={save}>Save current search</button>{saved.map(item=><div key={item.id}><button type="button" onClick={()=>loadSaved(item)}>{item.name}</button><button type="button" aria-label={`Rename ${item.name}`} onClick={()=>{const name=window.prompt("Rename saved search",item.name);if(name&&renameSavedSearch(window.localStorage,item.id,name,Date.now()))setSaved(loadSavedSearches(window.localStorage))}}>Rename</button><button type="button" aria-label={`Delete ${item.name}`} onClick={()=>{deleteSavedSearch(window.localStorage,item.id);setSaved(loadSavedSearches(window.localStorage))}}>Delete</button></div>)}</section><section><h2>Recent searches</h2>{recent.map(item=><Link key={item.path} href={item.path}>{item.label}</Link>)}{recent.length?<button type="button" onClick={()=>{clearRecentSearches(window.localStorage);setRecent([])}}>Clear history</button>:<p>No recent searches.</p>}</section><button type="button" onClick={()=>navigator.clipboard?.writeText(window.location.href)}>Copy shareable URL</button></aside>
    </section>
  </main>
}
