import type { AtlasEvent, AtlasEventCategory, AtlasSeverity, JsonValue } from "@/types/atlas-data";

export type ValidationResult<T> = { readonly ok: true; readonly value: T } | { readonly ok: false; readonly errors: readonly string[] };
const CATEGORIES = new Set<AtlasEventCategory>(["earthquake","cyclone","weather","space","technology","news","health","wildfire","flood","volcano","conflict","aviation","marine","market","cyber","energy","unknown"]);
const SEVERITIES = new Set<AtlasSeverity>(["info","low","moderate","high","critical","unknown"]);
const MAX_STRING = 10_000; const MAX_METADATA_BYTES = 100_000;
export function isIsoUtc(value: unknown): value is string { return typeof value === "string" && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/.test(value) && Number.isFinite(Date.parse(value)); }
export function isValidUrl(value: unknown): value is string { if (typeof value !== "string" || value.length > 2048) return false; try { const url = new URL(value); return url.protocol === "https:" || url.protocol === "http:"; } catch { return false; } }
function safeString(value: unknown, max = MAX_STRING): value is string { return typeof value === "string" && value.length > 0 && value.length <= max && !/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/.test(value); }
export function isJsonSafe(value: unknown, seen = new Set<unknown>(), depth = 0): value is JsonValue { if (depth > 20) return false; if (value === null || typeof value === "string" || typeof value === "boolean") return typeof value !== "string" || value.length <= MAX_STRING; if (typeof value === "number") return Number.isFinite(value); if (typeof value !== "object" || seen.has(value)) return false; seen.add(value); const valid = Array.isArray(value) ? value.length <= 1000 && value.every((v) => isJsonSafe(v, seen, depth + 1)) : Object.keys(value).length <= 1000 && Object.entries(value).every(([k,v]) => k.length <= 256 && isJsonSafe(v, seen, depth + 1)); seen.delete(value); return valid; }
export function validateCoordinates(value: unknown): ValidationResult<NonNullable<AtlasEvent["coordinates"]>> { const errors: string[] = []; if (!value || typeof value !== "object") return { ok:false, errors:["coordinates must be an object"] }; const c = value as Record<string, unknown>; if (typeof c.longitude !== "number" || !Number.isFinite(c.longitude) || c.longitude < -180 || c.longitude > 180) errors.push("longitude must be finite and between -180 and 180"); if (typeof c.latitude !== "number" || !Number.isFinite(c.latitude) || c.latitude < -90 || c.latitude > 90) errors.push("latitude must be finite and between -90 and 90"); for (const key of ["altitudeMeters","depthKilometers"] as const) if (c[key] !== undefined && (typeof c[key] !== "number" || !Number.isFinite(c[key]))) errors.push(`${key} must be finite`); return errors.length ? {ok:false,errors} : {ok:true,value:value as NonNullable<AtlasEvent["coordinates"]>}; }
export function validateAtlasEvent(value: unknown): ValidationResult<AtlasEvent> { if (!value || typeof value !== "object") return {ok:false,errors:["event must be an object"]}; const e=value as Record<string,unknown>; const errors:string[]=[]; for (const k of ["id","fingerprint","type","title","summary","status","sourceId","sourceName","attribution"] as const) if (!safeString(e[k], k === "summary" ? MAX_STRING : 1000)) errors.push(`${k} is invalid`); if (!CATEGORIES.has(e.category as AtlasEventCategory)) errors.push("category is invalid"); if (!SEVERITIES.has(e.severity as AtlasSeverity)) errors.push("severity is invalid"); for (const k of ["occurredAt","updatedAt","ingestedAt"] as const) if (!isIsoUtc(e[k])) errors.push(`${k} must be an ISO-8601 UTC timestamp`); if (e.expiresAt !== undefined && !isIsoUtc(e.expiresAt)) errors.push("expiresAt must be an ISO-8601 UTC timestamp"); if (!isValidUrl(e.sourceUrl)) errors.push("sourceUrl is invalid"); if (e.coordinates !== undefined) { const r=validateCoordinates(e.coordinates); if (!r.ok) errors.push(...r.errors); } if (!Array.isArray(e.tags) || !e.tags.every((t)=>safeString(t,100))) errors.push("tags are invalid"); if (!isJsonSafe(e.metadata)) errors.push("metadata is not JSON-safe"); else if (new TextEncoder().encode(JSON.stringify(e.metadata)).byteLength > MAX_METADATA_BYTES) errors.push("metadata is too large"); return errors.length ? {ok:false,errors} : {ok:true,value:value as AtlasEvent}; }
