"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import type {BreakingSnapshot} from "@/lib/breaking/breaking-contract";
const CATEGORIES=["all","earthquake","weather","volcano","disaster","conflict","economy","ai","cyber","space","health","marine","aviation","energy"] as const;
const ICONS:Record<string,string>={earthquake:"◉",weather:"☁",volcano:"▲",disaster:"△",conflict:"✕",economy:"▰",ai:"✦",cyber:"◌",space:"◎",health:"♥",marine:"≈",aviation:"✈",energy:"ϟ"};
export function BreakingNewsCenter({snapshot}:{snapshot:BreakingSnapshot}){
  const [category,setCategory]=useState<(typeof CATEGORIES)[number]>("all"),[priority,setPriority]=useState("all"),[country,setCountry]=useState(""),[provider,setProvider]=useState(""),[elapsed,setElapsed]=useState(0);
  useEffect(()=>{const update=()=>setElapsed(Math.max(0,Math.floor((Date.now()-Date.parse(snapshot.generatedAt))/1000)));update();const timer=window.setInterval(update,30_000);return()=>window.clearInterval(timer)},[snapshot.generatedAt]);
  const events=useMemo(()=>snapshot.events.filter(item=>(category==="all"||item.category===category)&&(priority==="all"||item.priority===priority)&&(!country||`${item.country??""} ${item.region??""}`.toLowerCase().includes(country.toLowerCase()))&&(!provider||item.providerId===provider)),[snapshot,category,priority,country,provider]);
  return <main className="breaking-page">
    <nav className="event-detail-back"><Link href="/app">← Global Overview</Link><Link href="/app/timeline">Global Timeline</Link></nav>
    <header className="breaking-hero"><div><p>BREAKING NEWS</p><h1>Verified Global Events</h1><span>Updated continuously from official providers. No generated headlines or summaries.</span></div><dl><div><dt>Last updated</dt><dd>{new Date(snapshot.generatedAt).toLocaleString()}</dd></div><div><dt>Provider count</dt><dd>{snapshot.providerCount}</dd></div><div><dt>Active breaking events</dt><dd>{snapshot.activeBreakingEvents}</dd></div></dl></header>
    {snapshot.partial&&<aside className="breaking-partial"><strong>{snapshot.stale?"Stale snapshot · not live":"Partial provider coverage"}</strong><span>Verified events from responding providers remain available. Missing events are not estimated.</span></aside>}
    <section className="breaking-status" aria-label="Current global breaking status"><strong>NOW</strong><div><span>Earthquakes</span><b>{snapshot.status.earthquakes}</b></div><div><span>Storms</span><b>{snapshot.status.storms}</b></div><div><span>AI Releases</span><b>{snapshot.status.aiReleases}</b></div><div><span>Space Events</span><b>{snapshot.status.spaceEvents}</b></div><small>Updated {elapsed<60?`${elapsed} sec`: `${Math.floor(elapsed/60)} min`} ago</small></section>
    <div className="breaking-categories" role="group" aria-label="Filter by category">{CATEGORIES.map(value=><button type="button" key={value} className={category===value?"active":""} aria-pressed={category===value} onClick={()=>setCategory(value)}>{value==="all"?"All":value[0].toUpperCase()+value.slice(1)}</button>)}</div>
    <section className="breaking-layout">
      <div>
        <div className="breaking-controls"><label>Priority<select value={priority} onChange={event=>setPriority(event.target.value)}><option value="all">All priorities</option>{["critical","high","medium","information"].map(value=><option key={value}>{value}</option>)}</select></label><label>Country / region<input value={country} onChange={event=>setCountry(event.target.value)} placeholder="Exact text filter"/></label><label>Provider<select value={provider} onChange={event=>setProvider(event.target.value)}><option value="">All providers</option>{snapshot.providers.map(item=><option value={item.providerId} key={item.providerId}>{item.providerName}</option>)}</select></label></div>
        <div className="breaking-feed" aria-live="polite">{events.length?events.map(item=><article className={`breaking-card priority-${item.priority}`} key={item.canonicalId} tabIndex={0}><header><b>{item.priority}</b><span>{ICONS[item.category]} {item.category}</span><em>VERIFIED</em></header><h2>{item.title}</h2><dl><div><dt>Country / region</dt><dd>{item.country??item.region??"Not supplied"}</dd></div><div><dt>Provider</dt><dd>{item.providerName}</dd></div><div><dt>Published</dt><dd><time dateTime={item.publishedAt}>{new Date(item.publishedAt).toLocaleString()}</time></dd></div><div><dt>Updated</dt><dd><time dateTime={item.updatedAt}>{new Date(item.updatedAt).toLocaleString()}</time></dd></div></dl><footer>{item.eventDetailUrl&&<Link href={item.eventDetailUrl}>Open Event</Link>}<Link href={item.timelineUrl}>Timeline</Link>{item.graphUrl&&<Link href={item.graphUrl}>Graph</Link>}<a href={item.sourceUrl} target="_blank" rel="noopener noreferrer">Official Source ↗</a></footer></article>):<div className="breaking-empty"><strong>No verified events match these filters.</strong><span>Adjust deterministic category, priority, country, or provider filters.</span></div>}</div>
      </div>
      <aside className="breaking-providers"><div><span>PROVIDER HEALTH</span><h2>Verified sources</h2></div>{snapshot.providers.map(item=><article key={item.providerId}><i className={`status-${item.status}`}/><div><strong>{item.providerName}</strong><span>{item.status.replaceAll("_"," ")}</span><small>{item.itemCount} records · {item.checkedAt?new Date(item.checkedAt).toLocaleTimeString():"Check unavailable"}</small>{item.message&&<p>{item.message}</p>}</div></article>)}</aside>
    </section>
    <footer className="breaking-method"><strong>Deterministic priority</strong><span>Earthquakes: ≥7.5 critical, 6.5–7.4 high, 5.5–6.4 medium. NOAA hurricane warnings: critical; tropical storms: high; other advisories: medium. Official AI agent/model major releases: medium; patches: information.</span><code>docs/ATLAS-BREAKING-NEWS.md</code></footer>
  </main>
}
